### ISSUE TITLE
SQLPro for Oracle end-of-file error

### ISSUE THREAD

**Issue by jngk2** [hankinsoft/SQLPro#354] opened 2020-01-28 11:09 UTC
Hi,

This is a valid PL/SQL query. The DECLARE section causes an error.

![image](https://user-images.githubusercontent.com/43384793/73258842-745c0200-41be-11ea-9a22-5031976318b0.png)

Does SQLPro for Oracle not support PL/SQL?

Thanks!
J

**Comment by hankinsoft** [comment] 2020-01-29 14:40
Unfortunately PL/SQL support is not 100%. I'll have to investigate this.

**Comment by hankinsoft** [comment] 2020-02-27 16:49
Hi -- would this be the same issue as #271?

**Comment by hankinsoft** [comment] 2020-03-05 01:36
Could you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.23.app.zip and see if that does the trick?

**Comment by hankinsoft** [comment] 2020-03-05 10:51
Closing as a duplicate of #271.

**Closed by hankinsoft** 2020-03-05 10:51 UTC
