### ISSUE TITLE
Change the default 'CMD + C' Copy format

### ISSUE THREAD

**Issue by Budders** [hankinsoft/SQLPro#183] opened 2018-04-06 09:04 UTC
Coping table data is a regular part of my analytics flow (usually into a pre-formatted excel spreadsheet). So copying data as 'Tab separated' is much more useful, I can't find a way as setting that as the default (assign the CMD+C copy shortcut to it) as this seems to be reserved for 'Comma separated'. I would be nice to be able to set this in the preferences.

**Comment by chucksense** [comment] 2018-04-11 16:11
+1 for this.  I always have to right click and select the tab separated option and it's a bit annoying.

An easy way to make this happen would be to simply add the "Copy as Tab Separated" to the top menu, then we can use the macOS keyboard preferences to bind Cmd-C to that instead of the default Copy.  That way you don't have to add a setting in for it. :-)

**Comment by hankinsoft** [comment] 2019-03-28 12:47
Closing as a duplicate of https://github.com/hankinsoft/SQLPro/issues/17. I recently added this option to the iOS apps and based on that I think I've figured out the UI to add it to the macOS version. I should hopefully have it available in the coming weeks.

**Closed by hankinsoft** 2019-03-28 12:47 UTC

**Comment by hankinsoft** [comment] 2019-04-03 11:32
The latest version of SQLPro Studio and SQLPro for Postgres both allow you to pick the default separator and delimiter for copy from results grid. If anyone gets a chance, please give it a try and let me know if that does the trick. Preference can be set from the 'Preferences' -> 'Keyboard' tab. Please leave any responses in #17.
