### ISSUE TITLE
Question: Autocomplete suggesting JOIN conditions for foreign keys

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#657] opened 2021-06-18 20:03 UTC
Saw that this was in the release notes for 2021.58. Sounds like an awesome feature!!

Does this only support some DBs? How does it work? I've been unable to trigger it

**Comment by hankinsoft** [comment] 2021-06-19 12:19
Hi,
This should support all database, however I think there is a bug where if the 'autocomplete cache' is already loaded then the foreign keys are not being loaded. You should be able to force them to be loaded by right clicking on the database and choosing refresh - they also get loaded into the cache when querying a table (just for the individual table).

I'm working on getting the cache bug fixed for the next build.

Is that what you mean by trigger it? Or do you mean the syntax requirement for autocomplete? If #2, then they appear only in simple cases such as:

SELECT <whatever> FROM <joins should appear>   or
SELECT <whatever> FROM sourceTable <joins should appear> or
SELECT <whatever> FROM sourceTable JOIN <joins should appear>

Those are currently the only three cases which will include joins as a suggestion.

**Comment by hankinsoft** [comment] 2022-01-13 20:47
> This would be great.

You should already be seeing these suggestions… they’ve been in the app for ~6 months. Do you not see them?

**Comment by jim256** [comment] 2022-01-13 21:00
No. I've never seen them. That's why I posted it as question and my first message said:

> Saw that this was in the release notes for 2021.58. Sounds like an awesome feature!!
> 
> Does this only support some DBs? How does it work? I've been unable to trigger it

And my Jul 9 message said:

> If I type the following query:
> 
> ```
> SELECT
> 	*
> 
> FROM
> 	alert_conditions ac JOIN subscriptions subs ON ac.id = subs.alert_condition_id
> ```
> 
> I don't ever get any foreign-key suggestions at any point.

Would love to know how to have these suggested!

**Comment by hankinsoft** [comment] 2022-01-14 14:41
Hmmm, ok. I'm going to add a debug command for the next build that will help me figure out why your not seeing them. Also, just to check if you connect to the sample northwind mysql database, do you see them there?

<img width="927" alt="Screen Shot 2022-01-14 at 10 40 30 AM" src="https://user-images.githubusercontent.com/3160528/149533537-247f7feb-06cf-4b6f-a80c-cadd7ad3d4a0.png">

**Comment by hankinsoft** [comment] 2022-01-15 19:55
In addition - using the latest build, could you do a:

`SELECT * FROM `

Leave your cursor after the whitespace after the from, right click, choose 'Debug' -> 'Autocomplete'.
A JSON file will be presented which contains a bunch of debugging information (list of entries it generated and foreign keys that were loaded mainly) for me. Please post (or email to kyle@hankinsoft.com referencing this issue).

Thanks!

**Comment by jim256** [comment] 2022-01-20 18:20
It does work for the sample Northwind DB. It still doesn't work for MySQL 8 (or Snowflake). 
[Debug file attached (as .txt so Gitub would accept it)](https://github.com/hankinsoft/SQLPro/files/7907606/debug_json.txt)
.

Also, as a side question, does the app use the ODBC connector for Snowflake, JDBC,...? Asking since the Snowflake ODBC connector doesn't work with the new M1 MacBooks.


SQLPro Studio 2022.5 (Build 110878.5)
macOS 12.1 (21C52)
MySQL 8.0.25

**Comment by hankinsoft** [comment] 2022-01-21 17:22
Hmmm, no foreign keys are loaded.

Some questions:
1. Is this your mysql connection?
2. What is the database engine? (is it InnoDB)?
3. If you right click and alter the table and switch to the foreign keys tab, does it show any?
4. If you run the following query:

```
SELECT
  DISTINCT
  i.TABLE_NAME,
  i.CONSTRAINT_TYPE,
  i.CONSTRAINT_NAME,
  k.REFERENCED_TABLE_NAME,
  k.REFERENCED_COLUMN_NAME,
  k.COLUMN_NAME,
  c.UPDATE_RULE,
  c.DELETE_RULE
FROM
  information_schema.TABLE_CONSTRAINTS i
INNER JOIN
  information_schema.KEY_COLUMN_USAGE k ON i.CONSTRAINT_NAME = k.CONSTRAINT_NAME
INNER JOIN
  information_schema. REFERENTIAL_CONSTRAINTS c ON c.CONSTRAINT_NAME = k.CONSTRAINT_NAME
WHERE i.CONSTRAINT_TYPE = 'FOREIGN KEY'
AND i.TABLE_SCHEMA = DATABASE()
ORDER BY ORDINAL_POSITION ASC
```

Do you receive any results?

**Comment by jim256** [comment] 2022-01-24 19:04
> Is this your mysql connection?

Yes

> What is the database engine? (is it InnoDB)?

InnoDB

> If you right click and alter the table and switch to the foreign keys tab, does it show any?

Negative

> If you run the following query ... Do you receive any results?

I receive the following:
+---------------+-----------------+-------------------------------------+-----------------------+------------------------+--------------------+-------------+-------------+
| TABLE_NAME    | CONSTRAINT_TYPE | CONSTRAINT_NAME                     | REFERENCED_TABLE_NAME | REFERENCED_COLUMN_NAME | COLUMN_NAME        | UPDATE_RULE | DELETE_RULE |
+---------------+-----------------+-------------------------------------+-----------------------+------------------------+--------------------+-------------+-------------+
| subscriptions | FOREIGN KEY     | FK_subscriptions_alert_condition_id | alert_conditions      | id                     | alert_condition_id | NO ACTION   | NO ACTION   |
| subscriptions | FOREIGN KEY     | FK_subscriptions_user_id            | users                 | id                     | user_id            | NO ACTION   | NO ACTION   |
+---------------+-----------------+-------------------------------------+-----------------------+------------------------+--------------------+-------------+-------------+

**Comment by hankinsoft** [comment] 2022-01-28 14:00
I've submitted a build v2022.7 with an additional debugging tool for the foreign keys:

![CleanShot 2022-01-28 at 09 56 23](https://user-images.githubusercontent.com/3160528/151559210-e1076608-8601-4339-8d79-5b01e17c1a7c.gif)

Right click on the query window, choose 'Debug', 'Load foreign keys'. This will force a re-load of the foreign keys for the database connection being used in the query window and then display the logs during that portion, including if an error occurs and how many keys were loaded.

You can ignore `Warning: Query is being executed on main thread. This will only be reported once per application.` warning.

Can you post the results of doing this for both your MySQL and Snowflake connection? The build should be available within ~24 hours.

**Comment by jim256** [comment] 2022-02-01 17:50
Unfortunately, I can't connect to Snowflake with my M1 MacBook, hence my previous question. I wasn't sure if I should reopen #681 or create a new one. Attempting to connect always results in: 
<img width="232" alt="image" src="https://user-images.githubusercontent.com/15026225/152021966-d595e567-b6be-4854-bff7-fb39e43ffd2b.png">
, though it does recognize the host as being online.

[com.hankinsoft.osx.sqlprostudio 2022-02-01--17-45-36-669.log](https://github.com/hankinsoft/SQLPro/files/7980765/com.hankinsoft.osx.sqlprostudio.2022-02-01--17-45-36-669.log)

Output of 'Debug' -> 'Load foreign keys':
```
Entering debugLoadForeignKeys
Warning: Query is being executed on main thread. This will only be reported once per application.
Looking for connection in pool. (38BAC6762938538BF4AED06BCF95AE54). Is user: no, clientId: <null>
Reusing connection from pool (38BAC6762938538BF4AED06BCF95AE54).
executeQuery:... find connection took 0.00 seconds.
executeQuery:... performQuery (MySQLAlterForeignKeysLogic:loadAllForeignKeys:error:) took 0.03 seconds.
releaseConnection: entered (38BAC6762938538BF4AED06BCF95AE54). UUID: <nil>
releaseConnection: (0675F819-D342-408E-B698-3A5F6E4853E9-939-00000087BBA729CC) to database pool.
releaseConnection: Pool 38BAC6762938538BF4AED06BCF95AE54 now has 2 entries.
releaseConnection took 0.00 seconds.
MySQLAlterForeignKeysLogic:loadAllForeignKeys:error: - Failed to load foreign keys with error: Expression #1 of ORDER BY clause is not in SELECT list, references column 'information_schema.k.ORDINAL_POSITION' which is not in SELECT list; this is incompatible with DISTINCT. (Error #3065)
SQLProForeignKeyCache:setForeignKeys:forDBC: - setting dbc 0675F819-D342-408E-B698-3A5F6E4853E9-939-00000087BBA729CC (MySQLDatabaseConnectionDetails) to have 0 keys.
Finished debugLoadForeignKeys
```

Looks like the 3rd-to-last line may have our answer!

**Comment by hankinsoft** [comment] 2022-02-08 16:10
The latest SQLPro Studio build is available and it should fix the mysql foreign keys. If you are still having an issue, please do the

> Right click on the query window, choose 'Debug', 'Load foreign keys'. This will force a re-load of the foreign keys for the database connection being used in the query window and then display the logs during that portion, including if an error occurs and how many keys were loaded.

And provide the results.

**Comment by jim256** [comment] 2022-02-08 18:01
The very first time I tried it, it didn't suggest it, but after I tried that (with the following output), ti works, even after quitting and re-launching the app:

```
Entering debugLoadForeignKeys
Warning: Query is being executed on main thread. This will only be reported once per application.
Looking for connection in pool. (38BAC6762938538BF4AED06BCF95AE54). Is user: no, clientId: <null>
Reusing connection from pool (38BAC6762938538BF4AED06BCF95AE54).
executeQuery:... find connection took 0.00 seconds.
executeQuery:... performQuery (MySQLAlterForeignKeysLogic:loadAllForeignKeys:error:) took 0.05 seconds.
releaseConnection: entered (38BAC6762938538BF4AED06BCF95AE54). UUID: <nil>
releaseConnection: (0675F819-D342-408E-B698-3A5F6E4853E9-939-00000087BBA729CC) to database pool.
releaseConnection: Pool 38BAC6762938538BF4AED06BCF95AE54 now has 1 entries.
releaseConnection took 0.00 seconds.
MySQLAlterForeignKeysLogic:loadAllForeignKeys:error: - Loaded 2 foreign keys.
SQLProForeignKeyCache:setForeignKeys:forDBC: - setting dbc 0675F819-D342-408E-B698-3A5F6E4853E9-939-00000087BBA729CC (MySQLDatabaseConnectionDetails) to have 2 keys.
Finished debugLoadForeignKeys
```

That said, it sometimes wants to directly insert a JOIN instead of a base table first.

I'm suggested:
<img width="848" alt="image" src="https://user-images.githubusercontent.com/15026225/153048019-cfdbfb3e-4b39-4de1-9e51-30f92867ba15.png">

If I accept, I'm given:
<img width="767" alt="image" src="https://user-images.githubusercontent.com/15026225/153048027-b490a5dc-859f-4ddb-b9f5-053d16e9602e.png">

**Comment by hankinsoft** [comment] 2022-02-08 18:20
> The very first time I tried it, it didn't suggest it, but after I tried that (with the following output), ti works, even after quitting and re-launching the app

That makes sense... the keys are cached and only reload after a specific time, or if a table modification is noticed. Running the debug method also forces a reload of keys.

> That said, it sometimes wants to directly insert a JOIN instead of a base table first.

Does this happen all the time? Or just sometimes? Have you noticed anything specific as to when it happens?

Also, FYI I'm submitting a build with snowflake fixed on m1 - I was able to reproduce it on one system.

**Comment by jim256** [comment] 2022-02-08 18:46
It only happens sometimes. I haven't noticed any pattern yet 🤔 If I do, I'll post here.

That's excellent news on the M1 support! I was just about to open an issue. I got one a few weeks ago and it's been pretty painful switching from an app as well done as SQLPro Studio to Snowflake's web UI.

Also, would you expect any of the foreign-key improvements you made for MySQL to also apply to Snowflake?

**Comment by jim256** [comment] 2022-02-11 20:32
SQLPro Studio connected to Snowflake seems to be working great on my M1!

It seems like the suggested joins feature is improving, though there are a few more issues:

1. If I alias my table, for example, before doing `JOIN`, then:
MySQL 8: the suggestion works, but it doesn't use my alias
Postgres 10.17: I don't get any suggestions

2. In Snowflake, if I have multiple schemas in one database, it looks like I have to run `USE SCHEMA [SCHEMA_NAME]` prior in order for it to suggest joins. 

3. If I use my MySQL connection and use Debug -> Load foreign keys, and then switch to a tab with my Postgres connection, I also need to use Debug -> Load foreign keys there for that connection. If I switch back to my MySQL connection, I have to do Debug -> Load foreign keys there again, even though I just did it in that tab for that connection a minute earlier.

4. Regarding your last comment, this also happens (though not every time) for me if I do
```
SELECT
	*

FROM
	[WAIT FOR AUTOCOMPLETE]
```

**Comment by hankinsoft** [comment] 2022-02-18 13:29
> If I write my SQL as above, as the built-in formatter would have me do it, nothing is ever suggested if I don't start typing the first character of a table name. I only get suggestions after FROM if I keep my cursor on the same line as FROM.

Item 5 is a byproduct of https://github.com/hankinsoft/SQLPro/issues/394#issuecomment-656339131

> I would personally prefer to never have autocomplete suggest anything after a hard return. In both of the examples above, I would prefer no suggestions until I begin to type something. I personally don't want suggestions until I begin typing.

Currently whitespace is not considered either after the hard-return.

Reproduced item seven and am working on a fix.

**Comment by hankinsoft** [comment] 2022-02-18 14:37
Seven is fixed for the next build.
Reproduced item 3. Working to figure out what's up with that.

**Comment by hankinsoft** [comment] 2022-02-18 14:50
For the next build item 3 and 7 are sorted.

**Comment by hankinsoft** [comment] 2022-02-18 14:57
> If I alias my table, for example, before doing JOIN, then:
> MySQL 8: the suggestion works, but it doesn't use my alias
> Postgres 10.17: I don't get any suggestions

I'm not currently planning on joins to work with aliases (I might add that in the future). I'll resolve the 'buggy' entries that are currently being added.

**Comment by jim256** [comment] 2022-05-10 00:16
Awesome to see this moving forward.

That said, I'd really love to see it work with aliases. I don't ever write a JOIN without using aliases, so for me the feature will go unused without that.

Two more things I noted:

1. With the following Snowflake 6.14.0 query, autocomplete will suggest expected joins, one being "INVENTORIES":
```
SELECT
	*

FROM
	[SCHEMA_NAME].PRODUCTS
	JOIN 
```
But if I start to type "INV" right after "JOIN" , it will not suggest any joins (though will offer a suggestion to complete the table name).
The behavior is the same regardless of whether or not I qualify it with the schema name.
I get the suggested joins if I don't type anything, but if I start typing to narrow it down, I don't get any join suggestions.

2. I don't get any join suggestions on Postgres 10.18 or 11.13 if I type anything after "FROM", though it will show plenty if I just leave the cursor after "FROM ".


macOS 12.3.1 (21E258)
SQLPro Studio 2022.33 (Build 110900.5)

**Comment by jim256** [comment] 2022-07-20 18:25
Just wanted to check in here and report that my team isn't able to use this feature still, but it would sure be awesome to have.

**Comment by hankinsoft** [comment] 2023-02-17 14:25
Just to check, the last feature remaining for this is autocomplete joins via alias's?

**Comment by jaredx435k2d0** [comment] 2023-02-22 16:57
I believe so.

That said, since my whole team is forced to switch off SQLPro in a week or due to no MFA/SSO support, I'm not sure if you want to dedicate cycle to this or not.

**Comment by jaredx435k2d0** [comment] 2023-02-22 16:57
Speaking of which, what are the top 2 alternatives you'd recommend for Mac users?

**Comment by hankinsoft** [comment] 2023-02-22 17:15
No worries. I'll go ahead and close this unless I get additional requests for it.

> Speaking of which, what are the top 2 alternatives you'd recommend for Mac users?

Not really such which ones would support MFA/SSO for Snowflake, so it's not something I could comment on. Hope you find something which works well for the team.

**Closed by hankinsoft** 2023-02-22 17:15 UTC
