### ISSUE TITLE
Master-detail separator slider resets

### ISSUE THREAD

**Issue by gitjoost** [hankinsoft/SQLPro#641] opened 2021-05-23 16:51 UTC
The vertical slider separating the database column on the left and the database detail on the right resets to its default position every time the application is restarted. Annoying as it defaults to approx 25% of the real estate and must be adjusted every time. Why not remember the position where the user left it?

**Comment by hankinsoft** [comment] 2021-05-23 18:35
Hi,
Is this for SQLPro Studio? If you change the 'Application Shutdown' preference to 'Save state' the sidebar state should be remembered between opening and closing the application. Please let me know if that helps you out.

**Comment by gitjoost** [comment] 2021-05-23 18:53
I don't seem to have that setting. This is SQLPro for SQLite 2021.34 build 4231.5

**Comment by hankinsoft** [comment] 2021-05-28 00:22
Going to close this as a duplicate of #411. I'll take a look at adding it for one of the upcoming builds.

**Closed by hankinsoft** 2021-05-28 00:22 UTC
