### ISSUE TITLE
Bug: Sidebar does not retain resized width

### ISSUE THREAD

**Issue by tsuliwaensis** [hankinsoft/SQLPro#411] opened 2020-04-15 01:57 UTC
In SQLPro for SQLite when you shrink or widen the Sidebar's width, the new width doesn't stick for any other databases opened, and it doesn't remember the resized positions when opening and closing the app.

**Comment by hankinsoft** [comment] 2020-06-30 13:03
I'm looking into adding this. In your opinion should the sidebar stay constant 'per database'? Or thought the app in general no matter which database you are opening? I think I would be ok with either.

**Comment by tsuliwaensis** [comment] 2020-08-29 14:44
Apologies for the delayed response. I think it should be a global setting. Thanks.

**Comment by hankinsoft** [comment] 2021-05-28 00:23
Had another user request this as well. I'll be taking a look into adding it shortly.

**Comment by hankinsoft** [comment] 2022-01-12 14:40
Sidebar position will be stored/restored based on the filename in the next build. So if you have the two files:

~/Documents/bob.sqlite
~/Documents/bob2.sqlite

These will NOT store the same position, but:

~/Documents/testing/bob.sqlite
~/Documents/bob.sqlite

I'm still investigating having the results panel store its size.

**Comment by hankinsoft** [comment] 2022-01-12 18:55
Setapp build submitted - should be available tomorrow at the latest. It will roll out to the website and App Store later this week.

**Comment by jmadren** [comment] 2022-01-28 22:50
Saving/restoring window & pane sizes works great, except when you open the db using the Open Recent menu. Then it reverts to some default (small window, large table pane - or it will be large once window is enlarged).

**Comment by hankinsoft** [comment] 2022-04-01 11:51
This should be resolved as of the latest build. Are you still seeing this?

**Comment by jmadren** [comment] 2022-04-01 12:51
For some databases, it is working. But for others not, and not just for databases opened with the Recent menu. Opening the db from Finder does the same. Is there some settings or cache that needs deleting?

Just to make sure I have the latest - mine is 2022.12 (Build 4252).

**Comment by tsuliwaensis** [comment] 2022-04-01 13:06
Is the latest build 2022.12 (build 4252.5)?

**Comment by hankinsoft** [comment] 2022-04-01 14:17
@tsuliwaensis 
> Is the latest build 2022.12 (build 4252.x)?
Yep, thats the latest build. 2022.12. The App Store version will end in .5 for the build where the website and setpp versions will not.

@jmadren 
> For some databases, it is working. But for others not, and not just for databases opened with the Recent menu. Opening the db from Finder does the same. Is there some settings or cache that needs deleting?

Just to confirm, the sidebar position is saved PER database. So if you open a database, set the position, then open a different database, it will NOT restore to the position you just saved.

**Comment by hankinsoft** [comment] 2022-04-01 14:37
> And after further testing, my problem is that some databases don't remember their window size

ooooooo, no you can leave it here. I'll fix that!

**Comment by hankinsoft** [comment] 2022-04-01 18:42
If anyone gets the chance, could they try:
https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.2022.19.app.zip

If that works properly, I will get the App Store and setapp versions updated as well.

**Comment by jmadren** [comment] 2022-04-01 22:39
Ok, at first it wasn't saving anything (window size or sidebar position). But after opening/closing a couple of databases a few times, it started saving the window size, but not the sidebar position. But then I discovered that it was applying the sidebar position of the last opened file to the newly opened one (I kept going back and forth between two files). And then I discovered that if I save the db before closing it, then everything is remembered correctly.

I'm thinking that the initial wonkiness was related to how long I had a file open or something that forced it to "autosave" the information.

I don't know if this is by design, but I would expect it to save the size information each time it is closed, whether I "saved" the file or not.

This does make me wonder, how are you saving this size information? If in the db, then that explains why the modified time changes every time I open a db. I always found that irritating, if I only opened it to view some data and didn't actually make any changes. It makes version control somewhat useless. (Note, some other SQLite browsers don't change the modified time if I don't actually change any data).

**Comment by jmadren** [comment] 2022-04-01 22:44
Well, I thought the save function was making everything work, but I was wrong. It's still wonky, and I'm not sure exactly what's going on.

**Comment by hankinsoft** [comment] 2022-04-01 22:53
> Well, I thought the save function was making everything work, but I was wrong. It's still wonky, and I'm not sure exactly what's going on.

Hmmm, save function should not be tied to the updating at all. It saves the window details when the document is closed - not to the database, but to the NSUserDefaults (nothing to do with the sqlite files).

> But then I discovered that it was applying the sidebar position of the last opened file to the newly opened one (I kept going back and forth between two files). And then I discovered that if I save the db before closing it, then everything is remembered correctly.

Are the two databases the same file name?

**Comment by hankinsoft** [comment] 2022-04-01 22:56
Hmmm, I might have figured something out. Investigating.

**Comment by hankinsoft** [comment] 2022-04-04 13:28
Can you try: https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.2022.20.app.zip?

**Comment by jmadren** [comment] 2022-04-04 14:06
Still wonky. Seems to be restoring the window size correctly, but not the sidebar width. If I close and then reopen the same db, then the sidebar width is restored correctly. But if I open another db, then the sidebar width is wrong (and it's not the same as the previous db as I thought it was earlier). The results are the same from Finder and from the Recents list.

To your earlier question, no, I was/am using two differently named database files.

**Comment by tsuliwaensis** [comment] 2022-04-04 14:15
FWIW, this works for me. Sidebar size is saved across sessions. Thank you

**Comment by hankinsoft** [comment] 2022-04-04 14:31
FYI, I've finally been able to reliably reproduce this.

**Comment by hankinsoft** [comment] 2022-04-04 15:38
https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.2022.22.app.zip?

**Comment by jmadren** [comment] 2022-04-04 19:04
You got it this time!

On a side note, I get a strange error from macOS warning when I open a db (from Finder) like it thinks the db is an unsigned/unnotarized app. Been doing that ever since the first zip file you provided.

![ScreenShot 2022-04-04 at 14 59 03](https://user-images.githubusercontent.com/22791228/161613228-65483a7e-3bed-4bda-9bf6-23ba01631bed.png)

Also, these versions (from your zip download) say it's a trial. I assume that will go away when it gets updated properly through Setapp? And maybe the file warning as well?

**Comment by hankinsoft** [comment] 2022-04-05 18:07
The setapp build (2022.23) has been approved and should be available for update anytime now. Once its available and you confirm everything is good, I think we should be ok to close the issue?

**Comment by jmadren** [comment] 2022-04-05 22:39
Yes, the SetApp version fixed the license and warning issues for me. Thanks!

**Closed** 2022-04-06 15:47 UTC
