### ISSUE TITLE
Feature Request: Central credentials for multiple connections

### ISSUE THREAD

**Issue by dlitty** [hankinsoft/SQLPro#770] opened 2022-04-19 21:05 UTC
In our organization we are being forced to change our database passwords more often than we used to be; this is somewhat of a pain since in SQLPro we have to edit each connection to do it.   It would be a lot more convenient if we had a separate area to update a credential, then for each connection, have that point to one of the "central" credentials.   The central area for credentials would still have to have multiple entries, but it would be far smaller (at least in my case) than the list of database connections.

**Comment by hankinsoft** [comment] 2022-04-20 11:21
Closed as a duplicate of https://github.com/hankinsoft/SQLPro/issues/503. Its on the backlog, but not ETA at the moment.

**Closed by hankinsoft** 2022-04-20 11:21 UTC
