### ISSUE TITLE
SQLPro for SQLite crashes when opened

### ISSUE THREAD

**Issue by muthuveerappanal** [hankinsoft/SQLPro#897] opened 2023-04-11 16:18 UTC
When app is opened, app crashes.

### Environment
**App:** SQLPro for SQLite version 2023.31 (Mac App Store version)
**macOS:** 13.3.1 (22E261)

It would be great to have a fix at the earliest or at least some work around. Thanks

**Comment by hankinsoft** [comment] 2023-04-11 16:28
Fix has been submitted and should be available by tomorrow. You could download https://www.sqlitepro.com/download.php and use the website/trial version until tomorrow. Sorry for the inconvenience. Closed as a duplicate of #895.

**Closed by hankinsoft** 2023-04-11 16:28 UTC
