### ISSUE TITLE
Lost Server

### ISSUE THREAD

**Issue by py-nux** [hankinsoft/SQLPro#834] opened 2022-09-12 08:02 UTC
**Describe the bug**
Lost of Register Server 

**To Reproduce**
Is Random , sometime we lauch the logiciel and my server list some server is missing or group was lost

**Comment by hankinsoft** [comment] 2022-09-15 16:45
What app version are you using?

**Comment by py-nux** [comment] 2022-09-19 09:24
This morning , I have again lost some register server :
And some deleted server came back in the list I think is a problem with sync version

**Comment by hankinsoft** [comment] 2022-09-20 12:10
Can you make a copy of 'C:\Users\<Your user>\AppData\Roaming\SQLPro\MSSQLConnections.json', then next time your connections are missing check the file again and compare the contents? If the entry getting removed, or is it failing to load?

**Comment by py-nux** [comment] 2022-09-20 12:13
I use Mac OS version

**Comment by hankinsoft** [comment] 2022-09-20 12:14
Please answer the following:

Environment:

Device: [e.g. iPhone6, MacBook]
OS: [e.g. iOS8.1, macOS 11]
SQLPro app Version [e.g. 2022.x]
Target database server [e.g. MySQL, PostgreSQL, Microsoft SQL Server, etc]

**Comment by py-nux** [comment] 2022-10-06 12:55
Environement : Apple
Device : MacBook Pro M1 Max
OS : Mac OS 12.5.1
SQLPro for MSSQL  : 2022.72 (Build 115572.5) (Mac Apple Store Version)
Target database server : Microsoft SQL Server

I have already send this mail with this informations...

**Comment by hankinsoft** [comment] 2022-10-06 13:03
Thank you for providing those details. The app version number had not been received previously.

A few additional questions to help figure this out:

1. Roughly how many connections do you have?2. 
2. How many connection groups do you have?
3. Do you have iCloud keychain enabled.
4. Are you using the app on multiple devices?

**Comment by py-nux** [comment] 2022-10-06 13:08
> Roughly how many connections do you have?
> 2.How many connection groups do you have?
I have more of 10 Server resisted , with 2 groupes ( Recette And Production)
I manage my groupe but some morning when I reopen the app I Loss Groupes and some old server who have deleted repaired and some new server disapear 

> Do you have iCloud keychain enabled.
I don’t know I think yes
> Are you using the app on multiple devices?
For the moment only this MacBook

**Comment by hankinsoft** [comment] 2022-10-06 13:21
> I manage my groupe but some morning when I reopen the app I Loss Groupes and some old server who have deleted repaired and some new server disapear

Are you saying the whole group dissapeard?

Could you do the following:
1. Open the logs folder ('View' -> 'Logs').
2. Close SQLPro
3. Delete all logs.
4. Launch SQLPro
5. Post the log file? (You won't be able to email it to github issue - attachments need to be posted directly to the github website directly, or you can email it to kyle@hankinsoft.com).

**Comment by py-nux** [comment] 2022-10-11 08:10
I already send all information :/

Environement : Apple
Device : MacBook Pro M1 Max
OS : Mac OS 12.5.1
SQLPro for MSSQL  : 2022.70 (Build 115570.5) (Mac Apple Store Version)
Target database server : Microsoft SQL Server

**Comment by hankinsoft** [comment] 2022-10-11 11:19
> I already send all information :/

Yep, I'm all set for those details. Per the email chat, the Next time you lose a server, could you send me the updated log file again? I'll compare the two and see if I can figure out whats going on.

**Comment by py-nux** [comment] 2022-10-12 10:26
Hi today , I lost group but all server merge in the first group :/

**Comment by hankinsoft** [comment] 2022-10-12 10:35
Could you provide a screenshot and log file? You can email them to kyle@hankinsoft.com.

**Comment by hankinsoft** [comment] 2022-10-14 11:57
There is a new update available that has some new logging around connection groups. The next time you have a connection lost, or that connection have been moved around can you do the following:

Open the logs folder ('View' -> 'Logs').
Send the 'connections.log' file to kyle@hankinsoft.com

This connections.log keeps a more details log around connections loading/saving specifically and should help narrow down whats going on here.

**Comment by py-nux** [comment] 2022-10-24 08:15
Hi we lost Group 
I have normally 2 group (Production/Recette) , the groupe Recette was lost but server of this groupe was move in Production

**Comment by hankinsoft** [comment] 2022-10-24 10:15
Could you provide the connections.log file?

Open the logs folder ('View' -> 'Logs').
Send the 'connections.log' file to [kyle@hankinsoft.com](mailto:kyle@hankinsoft.com)

**Comment by gregsj** [comment] 2022-10-31 17:51
I'm having a similar issue with my connections losing all foldering. Seems to be reproducble after a restart of my computer.
Device: Macbook Pro
OS: OS 12.X, 13.0
SQLPro for Postgres: 2022.70 (Build 1047870)
Target database server: Postgres

I've sent an email with logs

**Comment by hankinsoft** [comment] 2022-11-01 13:30
@gregsj you are able to reliably reproduce this? Would you be able to:

1. Sort your connections out.
2. Delete the connections.log file.
3. Launch the app so that it logs the current state.
4. Reboot
5. Launch the app with the reproduced state, then provide the connections.log file?

**Comment by gregsj** [comment] 2022-11-01 17:35
@hankinsoft I tried but a reboot didn't reproduce this time. Not sure what the trigger is but it has happened many times. I'll grab logs again when it happens next. FYI I don't see a connections.log file only 
com.hankinsoft.osx.SQLProPostgres 2022-11-01--17-26-43-270

**Comment by gregsj** [comment] 2022-11-05 00:38
@hankinsoft got a repro. Sent you the log.

**Comment by gregsj** [comment] 2022-11-15 17:25
@hankinsoft any update?

**Comment by hankinsoft** [comment] 2022-11-15 17:36
I've updated the SQLPro for Postgres version to include the connections.log. Can you provide these the next time you see the connections update themselves?

**Comment by gregsj** [comment] 2022-11-23 00:07
@hankinsoft got another repro. Sent you the log pre delete after organizing and the log after repro (all groups are gone).

**Comment by DJFriar** [comment] 2022-11-23 03:53
I am having this issue as well. 

**Environment (please complete the following information):**

- Device: Mac Studio (2022)
- OS: macOS 13.0.1 (22A400)
- SQLPro Studio 2022.77 (Build 110948)

**Additional context**
I leave SQLPro running pretty much 24/7, but had noticed that my laptop didn't have the new connections I added on my Mac Studio. I didn't think anything of it at the time, but then today when I was on my Mac Studio I closed out all my open connection windows and opened a new one to work on a different project and that is when I noticed that all my connections I had added a few weeks ago were missing.

I updated to the latest version of the app about a week ago I believe. The prior version was 2022.15 (110886), and I had never experienced this issue prior to the version update.

I lost connections and groups and ordering; almost like it reverted back to an earlier backup.

Checking iCloud Drive -> SQL Pro Connection and Favorites are both empty. Last modified date is Oct 15, 2022 for Connections (which sounds right for when I last added a new connection). Oddly, I checked by Backblaze backup and there are no files from this location saved there (I do have files from other apps that store their data in iCloud so not sure why these weren't picked up).

I have attached my logfile as well. Note that I don't see a connections.log file either, but I am using the SQLStudio version, not the "for Postgres" one. In the log attached, I can point out the key log entries:

_2022/11/23 03:00:05:455  setCollectionEntries with 1 sections (12 entries)._ - This is when I opened the new window. Note it shows 12 entries (which was correct).
There are then a bunch of connection errors due to some bad entries (this is normal)
_2022/11/23 03:00:26:004  onRemoveSelectedConnection_ - This is when I removed one of the bad ones since I took that server offline. However, at this time it was already showing the reduced set of just 6 entries and had forgotten my new ones.
_2022/11/23 03:00:27:239  setCollectionEntries with 1 sections (6 entries)._ - And now the log file reflects that there are only 6 entries. :(

[com.hankinsoft.osx.sqlprostudio 2022-11-22--12-28-18-375.log](https://github.com/hankinsoft/SQLPro/files/10072629/com.hankinsoft.osx.sqlprostudio.2022-11-22--12-28-18-375.log)

**Comment by DJFriar** [comment] 2022-11-30 16:46
@hankinsoft Anything I can do to help expedite a solution to this? It is really messing with me as I have 15-20 different servers and they keep being forgotten.

**Comment by hankinsoft** [comment] 2022-11-30 17:42
Can you grab https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2022.99.app.zip? That should add the 'connections.log' file. Then the next time you see it happen, post that file, please.

**Comment by gregsj** [comment] 2022-12-01 18:18
@hankinsoft I sent you a connections.log file with a repro last week. Did you get it?

**Comment by DJFriar** [comment] 2022-12-01 20:25
> Can you grab https://sqlprostudio.s3.us-east-1.amazonaws.com/studio/SQLProStudio.2022.99.app.zip? That should add the 'connections.log' file. Then the next time you see it happen, post that file, please.

Just installed it. Will start gathering logs.

**Comment by hankinsoft** [comment] 2022-12-02 13:30
@gregsj yes, sorry I had a question about that. Are you seeing one connection disappear at a time, or do you have them all disappear at once? From the log I see:

loaded 6 groups and 15 connections to be sorted.
loaded 6 groups and 14 connections to be sorted.
loaded 6 groups and 13 connections to be sorted.

So it looks like (unless your removing a connection) one connection gets dropped every so often?

**Comment by gregsj** [comment] 2022-12-07 18:35
All my groups disappear and I believe I gain back connections that I had removed. At one point I was noticing a connection getting lost but not any longer

**Comment by hankinsoft** [comment] 2022-12-07 19:02
> All my groups disappear and I believe I gain back connections that I had removed. At one point I was noticing a connection getting lost but not any longer

If you see all the groups gone can you try instantly closing the app and re-launch it again and see if they appear? I THINK I may have just seen this happen to me. I'm trying to hunt down how/why.

**Comment by DJFriar** [comment] 2022-12-31 23:52
It did it again to me today. I tend to leave SQLPro open all the time. Today I closed a few windows down, decided to use my laptop to do this work from, opened SQL Pro there, and saw it had lost the correct setup again. Checked my desktop, and it was also incorrect.

The weird part is it is reverting to a set of servers that are pretty old and I have no idea where it is getting the list from (since there are a few deleted servers in there that re-appear).

The connections log is attached below, but note that the timestamp at the top was updated when I did the "quit and re-open" suggestion above. It had originally shown 11-19-2022 (I think, I'm going from memory), which predates when I installed the current version of the app.

Where could it be pulling the list of connections from?

This is the current state of the connections.log as of right now:
[connections.log](https://github.com/hankinsoft/SQLPro/files/10328121/connections.log)

**Comment by hankinsoft** [comment] 2023-01-03 17:37
> The connections log is attached below, but note that the timestamp at the top was updated when I did the "quit and re-open" suggestion above. It had originally shown 11-19-2022 (I think, I'm going from memory), which predates when I installed the current version of the app.

I've discovered that the log files get overwritten if the last access was more then 10 days ago. I'm changing this to be size based instead (each log file can grow to 10mb).

I was hoping the previous portion of the log would have told me if the connections were loaded from the local storeage rather than iCloud storage (that's my guess of whats going on here). I'm making some changes based on that thought, but I'm not 100% sure if thats whats going on.

**Comment by hankinsoft** [comment] 2023-02-01 12:23
I'm working on rolling out an update that I believe should help out with this issue. It will be rolling out over the upcoming week or so. Doing a slow rollout as making changes with connections is something that always needs a bit of extra care.

**Comment by hankinsoft** [comment] 2023-02-15 12:39
All of the latest builds should be out. Please let me know if you continue to see this issue.

**Closed** 2023-03-03 18:33 UTC
