### ISSUE TITLE
Stored Procedure OUT parameters are not added to editor windows when editing proc scripts

### ISSUE THREAD

**Issue by DM1145** [hankinsoft/SQLPro#946] opened 2023-11-08 20:08 UTC
When OUT parameters exist in redshift stored procedures and the stored proc is loaded into a SQL script window for editing, the application drops OUT parameters (those that return values from procedures) from the script.  Should the script in the window be executed to update the proc, the parameters are dropped from the proc unless they are manually added back.

Found in SQLPro Studio Version 2023.35 (Build 111030)

**Comment by hankinsoft** [comment] 2024-01-05 12:40
Closing as I have been unable to reproduce.

**Closed by hankinsoft** 2024-01-05 12:40 UTC
