### ISSUE TITLE
Issue with SSL connections

### ISSUE THREAD

**Issue by DaveSanders** [hankinsoft/SQLPro#584] opened 2021-02-10 15:34 UTC
This is a newer issue - it only started happening for me recently. I'm on v 2021.12 Build 110774.5

I have two connections to an Amazon Aurora MySQL database that both need to use a SSL cert to connect.  (amazon generated cert file). For each, when I launch the app and try to connect, they won't connect due to an SSL error.

If I look at the connection, it shows that it IS using SSL and references the correct cert file.  However, if I go into the connection, edit, Advanced, SSL Config and then click to locate the CA certificate again (even though its already in the text field), the connection will start working.

Also, to add: I can't just look at the SSH configuration screen where I see the file path and NOT select the file again. If I try that it won't connect. I have to browse to the cert file and select the same one again and THEN it will reset the connection properly.  It's as if the connection config is not locating the file even though it still has the path.

If I happen to have a query window / connection open when I restart the app, and try to run a query against the DB connection, it will give me this error in the query results:

```
Initializing connection...
Connection ready. Took 0.163 seconds.

SSL connection error: system lib. (Error #2026). 0.000 seconds.

Finished. Total time: 0.163 seconds.
```

Obviously its super annoying that every time I launch the app I have to go edit the connection again.  Only my SSL configured connections act this way.

**Comment by hankinsoft** [comment] 2021-02-17 13:25
Hmmm, ok. So to confirm:

1. You are using SSL NOT SSH tunnelling.
2. You have to re-pick the `Client Certification` field again, even though its populated.

Would it be possible to get a screenshot of your SSL configuration dialog?

**Comment by DaveSanders** [comment] 2021-02-17 19:25
1. Yes, SSL, not SSH
2. Sure thing!

![connection](https://user-images.githubusercontent.com/24434/108256779-e2f26180-712b-11eb-85f0-35ef2acf2caa.png)
![ssl-dialog](https://user-images.githubusercontent.com/24434/108256786-e554bb80-712b-11eb-83f1-6c1c9bbecfa3.png)

**Comment by vab3** [comment] 2021-03-03 17:10
I had a similar issue with an SSL connection in Version 2021.08 (Build 1047829.5) on MacOS 11.2.1 (20D75). 

The first time I had the issue, I had just updated to Big Sur, so I downloaded the latest version and then it worked. 

The second time I got an error -- something like "could not access server root certificate".  
I attempted to connect with psql, which worked.  
I tried res-electing the Server Root Certificate, which did not fix it.
Then re-selected Client Certification -- no luck. 
Then I re-selected Client Key, and it worked.

**Comment by blak3r** [comment] 2021-03-18 17:22
I am having the exact same issue.  I recorded a video of it happening as well. 
I can reproduce it every time by fully closing SQLProStudio.  So, it's some issue with initial loading. 

In case it's relevant I'm a SetApp customer.  I didn't feel comfortable posting it public-ally because of IPs... but if you email me blake.robertson + gmail i'll share it. 

### Log snippet when it fails (Operation not permitted)
```
2021/03/18 17:17:26:717  HSDispatchGroup enter com.hankinsoft.connectionWindowDispatchGroup
2021/03/18 17:17:26:717  doConnect calling getHost:andPort:forServer:userSpecifiedPort:
2021/03/18 17:17:26:717  doConnect self->internalDatabaseConnectionDetails createNewClient
2021/03/18 17:17:26:717  PQlibVersion version: 100004
2021/03/18 17:17:26:717  doConnect calling databaseClient->connect
2021/03/18 17:17:26:717  PostgresDatabaseClient connect called (PQlibVersion: v100004).
2021/03/18 17:17:26:805  Connection to database failed: could not read root certificate file "/Users/blake/Desktop/server-ca.pem": Operation not permitted
2021/03/18 17:17:26:805  doConnect databaseClient->connect finished
2021/03/18 17:17:26:805  checkSSHFingerprintError returning NO
2021/03/18 17:17:26:805  HSMinimumDelay need to wait 0.91 seconds (elapsed was 0.09).
2021/03/18 17:17:27:721  HSMinimumDelay after delay, elapsed is: 1.00 seconds.
2021/03/18 17:17:27:722  SQLProConnectingWindowController endSheetWithReturnCode: OK
2021/03/18 17:17:27:722  HSDispatchGroup leave com.hankinsoft.connectionWindowDispatchGroup
2021/03/18 17:17:27:722  Failed to connect with error: could not read root certificate file "/Users/blake/Desktop/server-ca.pem": Operation not permitted
2021/03/18 17:17:27:723  Clearing internal database connection details.
2021/03/18 17:17:30:679  Application is resigning activity.
```

No parallel logs messages appear when its successful so didn't include.

**Comment by hankinsoft** [comment] 2021-03-19 14:29
I think I see what's going on. The issue exists separately for both MySQL and PostgreSQL - I'm attempting to fix both for the next release.

**Comment by blak3r** [comment] 2021-03-19 14:51
Nice!

**Comment by hankinsoft** [comment] 2021-04-07 11:49
I've made some changes in the latest versions. You will potentially run into the issue one additional time (per connection), but once the files have been re-selected the issue should be sorted. If anyone continually sees this issue, please let me know - include your app (screenshot of about dialog would be best).

**Comment by DaveSanders** [comment] 2021-04-07 12:58
Yes! I noticed a week or two ago that I haven't had to do the process of resetting up the certificate, and assumed that an update must have been deployed. So far, I haven't seen a return of this problem, and it has definitely sped up my bouncing around different databases.

As far as I can tell, my problem is fixed and this can be closed, but I'll hold off closing in case there was something else @hankinsoft was still working on here.

Thanks for the fix!

**Comment by hankinsoft** [comment] 2021-04-07 13:14
Thanks! I'll leave this open for a couple days and if I don't hear any issues from anybody else, I will close the issue.

**Closed** 2021-04-12 11:58 UTC
