### ISSUE TITLE
SQLPro Studio, Feature Request: SQL Import

### ISSUE THREAD

**Issue by markbiek** [hankinsoft/SQLPro#603] opened 2021-03-24 18:05 UTC
It would be really nice to be able to import data from `.sql` files in addition to CSV.

While you _can_ open a `.sql` file with the query editor, this doesn't work well for large files. I've found that SQLPro Studio can take several minutes to open even a relatively small sql file (<200mb).

**Comment by hankinsoft** [comment] 2021-03-25 12:46
This has been requested a few times, so I'm adding it for the next build. Should be available early next week if not sooner.

**Comment by markbiek** [comment] 2021-03-25 13:11
Excellent, thank you!

Once that's in, the app will be absolutely _perfect_

**Comment by hankinsoft** [comment] 2021-04-07 11:15
SQL import is available in the latest SQLPro Studio build via the App Store. If you get a moment, please give it a try and let me know if it runs as expected.

**Comment by hankinsoft** [comment] 2021-04-12 12:00
Going to close this. Please feel free to re-open if you find issues. Note to self - duplicate of #603.

**Closed by hankinsoft** 2021-04-12 12:00 UTC

**Comment by markbiek** [comment] 2021-04-12 15:32
Sorry for the delay in responding. I've updated to the latest build & the import works great!
