### ISSUE TITLE
Can not save docs

### ISSUE THREAD

**Issue by kalmecak** [hankinsoft/SQLPro#99] opened 2017-05-26 18:23 UTC
After the app is working for a long time, it throws permission error on saving documents:

![captura de pantalla 2017-05-26 a la s 13 11 47](https://cloud.githubusercontent.com/assets/1189660/26507501/360992c4-4216-11e7-902d-7d79cd7101e0.png)

So I have to restar the app to make it works again.

**Comment by hankinsoft** [comment] 2017-05-26 18:30
Hi,
I have an open ticket with Apple about this issue. I've got a few steps I
can send shortly to try and help diagnose this, but in the meantime could
you let me know what version of macOS you are using?

**Comment by kalmecak** [comment] 2017-05-26 18:39
Of course, I'm using Mac OS Sierra v10.12.3

**Comment by hankinsoft** [comment] 2017-05-26 19:13
Would there be any chance you could upgrade to 10.12.5? One of the recent
messages from Apple was to ask if this build fixed the issue for users. I
haven't heard back from any users about this yet and that was about three
or four days ago. So it's possible this will resolve the issue.

**Comment by kalmecak** [comment] 2017-05-31 17:16
I already updated my Mac OS and seems it worked

**Comment by hankinsoft** [comment] 2017-05-31 19:23
Thank you very much for letting me know! I will pass this information onto
Apple as well!

**Comment by hankinsoft** [comment] 2017-05-31 20:56
Just to note, another customer just emailed stating they are still seeing
this on 10.12.5. They also provided some additional logging that Apple has
asked for, so hopefully progress can be made!

**Comment by kalmecak** [comment] 2017-06-21 16:11
Hi again!
I just want to update this issue, now I can not save/open any .sql files because it keeps saying I have no permissions, for now I'm opening these files in Atom and copy/pasting on SQLPro, this is the only way I can work at the moment :(

![captura de pantalla 2017-06-21 a la s 11 00 38](https://user-images.githubusercontent.com/1189660/27394394-966ed1dc-5671-11e7-92dc-e517a77f1e65.png)

**Comment by hankinsoft** [comment] 2017-06-21 18:17
Hi,
I unfortunately don't have a fix for this yet. The last conversation with apple is as follows:

"I showed the sysdiagnose to the App Sandbox engineers and they told me that the logging on macOS 10.12.5 is broken. Sandbox violations aren't logging backtraces like they should.

This has been fixed in the macOS 10.12.6 seed that is currently available. I know this is painful, but would your customer be willing to set up a macOS 10.12.6 beta system in order to reproduce this again and get a sysdiagnose that isn't missing information?"

Upon mentioning that customers cannot get the 10.12.6 beta without being developer, I was told that customers should wait until macOS 10.12.6 has been released and have them recreate sysdiagnose logs.

Very sorry for the issue and apologies on the time its taking to get this sorted out.

**Comment by kalmecak** [comment] 2017-06-21 19:15
Ok, I undertand, thanks!

**Comment by hankinsoft** [comment] 2017-07-20 12:40
Hi,
Apple has released macOS 10.12.6 and states that sysdiagnose logs should now include the logging that will fix this. Anyone who is seeing this issue, please do the following steps:

1. Upgrade to macOS 10.12.6 via the Mac App Store.
2. Use SQLPro until you receive the permission denied error (either saving, opening files, or exporting).
3. Create a sysdiagnose log. (See attached PDF for [instructions](https://github.com/hankinsoft/SQLPro/files/1162269/sysdiagnose_Logging_Instructions.pdf)).
4. Sysdiagnose files are fairly large. If you have a place to upload them, please do so and send me the link (kyle @ hankinsoft.com). If you do not, please let me know and I can provide you with a host for uploading the file.

Thanks!

**Comment by ericgrosz** [comment] 2017-09-19 18:50
Hi, any updates on this issue? Thanks!

**Comment by lancefisher** [comment] 2017-09-24 04:23
I'm getting this error on macOS 10.12.6. The folder I'm trying to save to is on Google Drive. Restarting SQL Pro Studio seems to have fixed it for now.

**Comment by benluck301** [comment] 2017-10-27 09:38
Hey, I get this problem very frequently. It's so frustrating because this product is brilliant. But everyday I have to relaunch it multiple times. I rebuild my mac from scratch last week, totally fresh, wiped all drives clean. The problem still occurs, I really hoped a full rebuild would make this go away. I using version 1.0.149 Build 1087, and am running macOS 10.12.6

**Comment by hankinsoft** [comment] 2017-11-10 18:30
Anyone using SQLPro Studio, please download build https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.1.0.152.app.zip and give it a try. I've had help from Apple DTS and I have applied a workaround which should resolve the issue. I currently only have this resolved for Studio, but if the does indeed solve the issue, I'll put out builds for the other products as well.

**Comment by bendoh** [comment] 2017-11-17 21:26
MacOS 10.12.6 w/ SQL Pro for MSSQL 1.0.185 (build 4341) – still experiencing this problem whenever I try to save or open a file.

**Comment by semerj** [comment] 2018-06-25 21:34
Just echoing the above. Problem persists on SQL Pro for Postgres version 1.0.133 (Build 282) on MacOS 10.12.6 😞

**Comment by hankinsoft** [comment] 2019-03-28 11:57
It's been awhile since I've seen or heard of this issue. I believe that the latests versions of macOS have sorted the problem. If anyone runs into this issue using Mojave or above, please feel free to let me know.

**Closed by hankinsoft** 2019-03-28 11:57 UTC
