### ISSUE TITLE
Query editor struggles with large queries

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#519] opened 2020-10-27 21:47 UTC
When dealing with really large queries (700+ lines), scrolling in the editor can get weird. Trying to rapidly scroll up with the touchpad will sometimes stop very suddenly (as if it thinks it's hit the top), even if it's hundreds of lines from the top.

SQLPro Studio 2020.88 (Build 110729.5)
macOS 10.15.7 (19H2)

**Comment by hankinsoft** [comment] 2020-10-28 11:30
When this happens does the scrollbar still work? Does page up/down work?

Also, what font do you have set for the query editor?

(I'm not able to reproduce this using a larger file, so I'm just trying to figure out what is different).

**Comment by jim256** [comment] 2020-11-04 18:37
Scrollbar works fine, though the size of the scrollbar decreases once I scroll all the way to the top.
Page up definitely skips / gets caught, similar to scrolling with touchpad.

No idea if this is helpful, but here is a log file of:
Disconnecting from all DBs
Closing all editors
Quitting the app
Deleting the log file
Opening the app
Hitting the "esc" key on the keyboard when the Connections window popped up
Hitting CMD + T for new tab
Hitting CMD + V to paste in long query
Scrolling using touchpad, then page up

[com.hankinsoft.osx.sqlprostudio 2020-11-04--18-32-06-043.log](https://github.com/hankinsoft/SQLPro/files/5489866/com.hankinsoft.osx.sqlprostudio.2020-11-04--18-32-06-043.log)

**Comment by hankinsoft** [comment] 2021-02-17 14:00
I've made quite a few changes with this recently. Could you see if you are still experiencing slowdowns in the latest version?

**Comment by jim256** [comment] 2021-02-19 21:42
Still happens with 2021.13 (Build 110775.5) on macOS 11.2.1 (20D74), though I think only when using the touchpad. Scrolling with a mouse, for example, works great. Scrollbar and page up/down seemed to work well.

I realized I didn't answer your font question:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/15026225/108559414-8a9c9a80-72b8-11eb-90f6-77613cc35f09.png">

**Comment by hankinsoft** [comment] 2023-08-08 18:59
Going to close this. If others continue to see slow performance with the query editor please let me know. Some sluggishness will be expected once you get to a certain size.

**Closed by hankinsoft** 2023-08-08 18:59 UTC
