### ISSUE TITLE
Not always Saving

### ISSUE THREAD

**Issue by manngo** [hankinsoft/SQLPro#794] opened 2022-06-11 23:55 UTC
A few times, I have found that I can’t save a new document.

If I have a new document it is, of course called `Untitled ….sql`. If I attempt to save it, the menu item highlights, but there is no `Save As…` dialog, and the document doesn’t save. I cant save it with with `Save As…` either.

The only solution is to quit and start again, after which it works well.

I can’t reproduce this behaviour reliably, though I have noticed that when I restart the application some previously autosaved documents are retained, and I can then save them as normal.

**Comment by hankinsoft** [comment] 2022-06-23 11:47
Duplicate of #807

**Closed by hankinsoft** 2022-06-23 11:47 UTC
