### ISSUE TITLE
Problem with connecting with SSH Tunneling (SQLPro for Postgres)

### ISSUE THREAD

**Issue by bartoszj** [hankinsoft/SQLPro#28] opened 2015-11-25 09:06 UTC
I've database on remote machine which is not accessible outside this machine, so I've to use SSL Tunneling. In The Valentina Studio I can use parameters below and connect to remote database.
- Host: localhost
- SSH Host: <ip address>
- SSH User: <user>

But with SQLPro for Postgres I'm receiving:
`External SSH tunneling cannot be used to connect to a servering running on localhost/127.0.0.1. Please replace host name with an external address.`

I cannot use external IP because it is blocked on the server. I've to use localhost or 127.0.0.1

**Comment by hankinsoft** [comment] 2015-11-25 12:35
Hmmm, so your ssh server and postgres server are on the same external machine? I hadn't though of that scenario. I'll make a fix for this.

**Comment by bartoszj** [comment] 2015-11-25 12:36
Hi,
Yes I've exactly the this scenario.

**Comment by hankinsoft** [comment] 2015-12-01 22:59
Can you try https://d3fwkemdw8spx3.cloudfront.net/postgres/SQLProPostgres16a.app.zip? It should sort the issue. Please let me know. If everything is confirmed, I will close this and submit the fix to the MAS. If you purchased via the mac app store, please email kyle @ hankinsoft.com for a license to use in the meantime.

**Comment by bartoszj** [comment] 2015-12-02 07:07
Unfortunately it doesn't help. If I create new connection, configure it (with SSH tunneling) and use "Save and Connect" I get:
```
Failed to connect to 'localhost' on port 5432. Connection refused.
```

If I try to connect from the "Connect" window I get:
```
(SSH) Failed to authenticate against remote server.
```

I'm not using public/private key for authentication and I'm using the same setting in the Valentina Studio without any problems.

**Comment by hankinsoft** [comment] 2015-12-05 18:36
Thanks for letting me know. I think I know whats going on. Are you using keyboard interaction?

**Comment by bartoszj** [comment] 2015-12-05 18:43
I don't really know what you mean by _keyboard interaction_? I'm providing SSH password in the application, so there should be no other interaction needed.

**Comment by chranmat** [comment] 2018-10-17 16:36
SQLPro for Postgres was recently updated through App Store. Now the problem seems to be solved..

**Closed** 2019-04-02 18:02 UTC
