### ISSUE TITLE
Unexpected EOF from the server (SQLPro for MSSQL)

### ISSUE THREAD

**Issue by AdamGerthel** [hankinsoft/SQLPro#422] opened 2020-05-03 09:31 UTC
I'm getting the following error when connecting to my MSSQL server:

<img width="443" alt="Screenshot 2020-05-03 at 11 24 36" src="https://user-images.githubusercontent.com/1490370/80910604-d3d32c00-8d30-11ea-95c7-b5440484579a.png">

Nothing has changed on the server afaik, but two things have changed since the last time I connected:

1. I got a new Macbook and migrated to it using the migration assistant.
2. I'm now on Catalina which doesn't support PPTP which I previously used to connect to the server, so I had to change to L2TP over IPSec.

I've double-checked all connection settings in SQLPro and everything seems to be correct.

**Comment by hankinsoft** [comment] 2020-05-04 16:09
Hi,
A few questions:

1. Are you specifying a host name or IP address?
2. Are you connecting to a named instance?
3. Are you specifying a port?

**Comment by AdamGerthel** [comment] 2020-05-04 16:14
@hankinsoft I've tried both using host name and IP. I've tried both by specifying port in the hostname and in the port field.

> Are you connecting to a named instance?

Not sure what this means.

**Comment by hankinsoft** [comment] 2020-05-04 16:16
A named instance would be if you were connecting such as:

myserver\somethingelse as part of your hostname.

Do you know what version of SQL Server is running on the host machine? Also, what version of windows if possible?

**Comment by hankinsoft** [comment] 2020-05-04 16:20
And the database is Microsoft SQL Server? Not MySQL or Postgres?

**Comment by AdamGerthel** [comment] 2020-05-04 16:30
@hankinsoft 

> A named instance would be if you were connecting such as

Ok, it's not a named instance. In fact, I have a database visualisation tool (Viur.com) which uses the exact same connection to the server (but not via VPN, the firewall allows it via UP), and that service has not lost connection. AFAIK it's only my new laptop which isn't able to connect anymore. The VPN tunnel works in other aspects (for example i can connect to the server via Remote Desktop).

> And the database is Microsoft SQL Server? Not MySQL or Postgres?

MSSQL. 200% certain :) It's been up and running on a Windows server for about 5 years now.

> Do you know what version of SQL Server is running on the host machine? Also, what version of windows if possible?

Microsoft SQL Server Management Studio						12.0.2269.0
Microsoft Analysis Services Client Tools						12.0.2000.8
Microsoft Data Access Components (MDAC)						6.3.9600.17415
Microsoft MSXML						3.0 4.0 6.0 
Microsoft Internet Explorer						9.11.9600.19678
Microsoft .NET Framework						4.0.30319.42000
Operating System						6.3.9600

Above was copied from "about" in Microsoft SQL Server Management Studio

**Comment by hankinsoft** [comment] 2020-05-04 16:40
> MSSQL. 200% certain :) It's been up and running on a Windows server for about 5 years now.

Sorry, had to ask :)

Can you email me the log file (after a failed connection)? You can find it by going to 'View' -> 'Logs'. Email via kyle @ hankinsoft.com.

**Comment by AdamGerthel** [comment] 2020-05-04 16:50
@hankinsoft sent!

**Comment by hankinsoft** [comment] 2020-05-04 17:16
Hmmm, nothing is sticking straight out. A few more questions if you get the chance:

1. Windows authentication or SA authentication?
2. Are you able to view the audit logins on the actual SQL Server? (https://www.netwrix.com/how_to_audit_sql_server_logins.html).

**Comment by AdamGerthel** [comment] 2020-05-04 19:55
1. SA authentication
2. Those instructions did not seem to work. There's no “Audits” under "Security", or I'm in the wrong place.

<img width="212" alt="Screenshot 2020-05-04 at 21 54 26" src="https://user-images.githubusercontent.com/1490370/81007633-e09b7100-8e51-11ea-9661-69480b71513e.png">

**Comment by petervizee** [comment] 2020-06-02 07:24
I migrated to a new MacBook and now I get the same Error Message. So I think the migration part is the issue and would like te reinstall the App. What files do I need to remove to completely uninstall (moving the App to the bin is nog enough, my License and connection are stille there). Please help!

**Comment by petervizee** [comment] 2020-06-03 05:37
Deleting everything named %sqlpro% and %hankin% from the harddisk and keychain deleted my license key, but not my connections so something is still being left behind...

Also after I migrated to a new Mac, I updated MacOS to version 10.15.5. In between I did not test SQLPro, so maybe it's an issue to do with the latest update of MacOS?

Please help, I am forced to work on SSMS via RDP now :-(

**Comment by hankinsoft** [comment] 2020-06-03 12:55
Hi,
A few questions:

1. What version of Windows is the SQL Server running on?
2. What version of SQL Server is running on the server?
3. Are you using Windows Authentication or SA authentication?
4. Are you able to find the audit logs if you RDP into the server? (https://www.netwrix.com/how_to_audit_sql_server_logins.html) - ideally if you can let me know what the audit logs are showing on the failed logins, that would be awesome.

**Comment by petervizee** [comment] 2020-06-03 13:11
Hi Kyle,

I use 2 SQL servers, both running on Windows 2008 R2, versions 2005 and 2008 (i know they are old, getting new servers in a few months).
I use SA authentication, but also tried Windows authentication.
Audits are unfortunately not available.
On the servers nothing changed, last friday it al worked fine. Over the weekend I migrated to a new MacBook and updated MacOS to 10.15.5 and now I only get this message...

I really hope you can help! Thank you in advance!

**Comment by AdamGerthel** [comment] 2020-06-03 13:12
FYI the issue is still unresolved for me as well

**Comment by hankinsoft** [comment] 2020-06-03 13:16
Could either of you try an older version of SQLPro Studio and see if that works?

https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.67.app.zip

Roughly ~4 months ago I upgraded the internal MSSQL connector, so I'm curious if the older version works. There is a newer version available as well, but it will take me up to a week to get it implemented.

**Comment by petervizee** [comment] 2020-06-03 13:25
No, I get the same message (after a long time "Connecting")...
FYI I use SQLPro for MSSQL (not Studio).

**Comment by petervizee** [comment] 2020-06-03 13:28
I also tried using another user-account on my Mac, which never used SQLPro before, and the issue is the same. Maybe that helps in some way...

**Comment by hankinsoft** [comment] 2020-06-03 13:33
Ok - I'm going to update the mssql driver and see if that helps out. I will post the updated build as soon as its available.

**Comment by hankinsoft** [comment] 2020-06-03 17:36
Could either of you try https://d3fwkemdw8spx3.cloudfront.net/mssql/SQLProMSSQLTesting.zip and see if that sorts the issue out?

**Comment by petervizee** [comment] 2020-06-03 17:40
Not for me I'm afraid... Still the same message for both servers

**Comment by petervizee** [comment] 2020-06-03 17:45
I was wondering how I could connect to the SQL server with another application. The only one I could think of I have is Excel. And using the SQL Server ODBC I could. Maybe it helps, if not please ignore :-)

![Excel1](https://user-images.githubusercontent.com/65186072/83669978-b95fcd00-a5d2-11ea-8971-45e0ebfb0929.png)
![Excel2](https://user-images.githubusercontent.com/65186072/83669986-bbc22700-a5d2-11ea-95b9-ee20153386e6.png)

**Comment by hankinsoft** [comment] 2020-06-03 18:23
Can you:
1. Close all instances of SQLPro.
2. Open termal.
3. run `defaults write com.hankinsoft.osx.tinysqlstudio ApplicationPreference-EnableFreeTDSLogging -bool YES` (this enabled additional logging with mssql).
4. Download https://d3fwkemdw8spx3.cloudfront.net/mssql/SQLProMSSQLTesting2.zip (this is a new version - I updated libssh which MIGHT fix the issue).
5. Run the downloaded version.
6. Try connecting.
7. If it fails, go to 'View' -> 'Logs'.
8. Close the application (this causes the logs to be flushed).
9. Send the resulting log file (it will be `freetds.pid#####.log`) to me via kyle @ hankinsoft.com?

Please be sure to use the version here: https://d3fwkemdw8spx3.cloudfront.net/mssql/SQLProMSSQLTesting2.zip.

**Comment by petervizee** [comment] 2020-06-03 18:37
YES! This version works! I am now connected to both servers.

![2020-06-03_20-34-36](https://user-images.githubusercontent.com/65186072/83675763-d8ae2880-a5d9-11ea-8c1e-c58d5b03225a.png)

Thank you very much Kyle, you're a star!!

**Comment by hankinsoft** [comment] 2020-06-03 18:38
Great! Can you run `defaults write com.hankinsoft.osx.tinysqlstudio ApplicationPreference-EnableFreeTDSLogging -bool NO` so that the extended logging is disabled.

**Comment by AdamGerthel** [comment] 2020-06-04 11:32
Works for me too!

**Comment by hankinsoft** [comment] 2020-06-04 12:02
Thank you! I'm going to leave this open for the moment as thats not an 'official' build (their might be some wonkeyness around autocomplete as #404 is partially implemented in that build). I hope to have the official build available next week.

**Comment by hankinsoft** [comment] 2020-06-19 11:15
The latest versions are now available all around. I'm going to close the issue. Please let me know if you need anything else.

**Closed by hankinsoft** 2020-06-19 11:15 UTC

**Comment by AdamGerthel** [comment] 2020-06-22 12:59
I just downloaded it from app store (Version 2020.48 (Build 10509.5)) but the issue is still there. Is a new release on its way?

**Comment by hankinsoft** [comment] 2020-07-02 12:16
> I just downloaded it from app store (Version 2020.48 (Build 10509.5)) but the issue is still there. Is a new release on its way?

Sorry, I forgot to post that the newest has been posted to the App Store. That should sort that out.

Also, I've been having quite a few reports of crashes specific to MSSQL since I've made this update. Because this update included two changes (first I updated FreeTDS, then I updated the ssl library), I'm going to try rolling out the FreeTDS change and see if that helps fix the issue -- just keeping the ssl update as I believe thats what sorted the EOF error. I'll be posting some test builds to #462 for some users to see if that sorts them out. This is more of a heads up that if you do see the EOF issue again, please be sure to let me know.
