### ISSUE TITLE
Crashing when importing huge CSV files

### ISSUE THREAD

**Issue by TGit911iger** [hankinsoft/SQLPro#513] opened 2020-10-12 07:35 UTC
Importing a CSV file > 2 MB crashes the app.

**Comment by hankinsoft** [comment] 2020-10-21 14:28
Hi,
I'm not able to reproduce this issue. If possible, could I get a copy of the CSV file?

**Comment by hankinsoft** [comment] 2021-01-06 18:34
Closed as non-responsive.

**Closed by hankinsoft** 2021-01-06 18:34 UTC
