### ISSUE TITLE
Feature Request: Cmd + Click Table Name in SQL Editor to Jump to Table Data / Definition

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#288] opened 2019-09-10 21:51 UTC
It would be great if table names (and perhaps other things) became clickable links when holding the Command button, such that clicking on them would take you to the table view. I've often found this feature very useful when writing queries in other apps when I need to take a look at the table really quickly and then get back to writing the query.

**Comment by hankinsoft** [comment] 2019-09-13 13:34
Closing as a duplicate of #169. I'm going to see if I can get this added for one of the next upcoming builds.

**Closed** 2019-09-13 14:23 UTC

**Comment by hankinsoft** [comment] 2019-09-16 17:27
Just to note that I updated #169 with a version that allows for right clicking a table name in the query editor and performing a few actions. If you get the chance, please give it a try and post any issues/requests on that item. Thanks!

**Comment by jim256** [comment] 2019-10-10 17:32
@hankinsoft, never saw that you'd done this. Awesome stuff! Very handy.
