### ISSUE TITLE
Export result set fails intermittently

### ISSUE THREAD

**Issue by msharp** [hankinsoft/SQLPro#186] opened 2018-04-11 02:54 UTC
Occasionally the "export result set" (as CSV) feature does not create a file.

There is no error message shown.

To export the result set I then have to quit and restart SQLPro and execute the query again.

I'm using:

  - OSX 10.12.6
  - SQLPro Studio 1.0.163 (Build 1123)

After it happened most recently, I found this in my syslog

`Apr 11 12:43:02 heracles SQLPro Studio[88377]: objc[88377]: __weak variable at 0x7ff0b5f197e0 holds 0x4019d92aaaaaaaab instead of 0x7ff0b3584af0. This is probably incorrect use of objc_storeWeak() and objc_loadWeak(). Break on objc_weak_error to debug.`

**Comment by hankinsoft** [comment] 2018-04-11 15:34
Hmmm, thats odd. I'm not able to reproduce at the moment, just to check a few things:

1. What type of database server? (MySQL, SQL Server, other)?
2. Any 'unique' type of data? Is it something other than text or numbers?
3. If you do a simple query such as SELECT 'hello', 'world' are you able to export those results?

Thank you!

**Comment by msharp** [comment] 2018-04-11 23:38
Yes, it's going to be an elusive one.

To be clear, I am normally able to export data.  But it just stops working at some point.  And then I need to restart the program to enable the feature again. 

In this case it was on a Postgres database.  Only text and number data, and only a few columns, but many rows (100,000+).

This has happened several times for me.  In the most recent case, I had the program running for several hours, happily selecting and exporting the same dataset (different data, same structure).  Then all of a sudden, it won't create the file.  No error or warning.  I can try again and again but it won't do it.

Save my query, restart the program, and it works.

**Comment by msharp** [comment] 2018-04-12 00:31
Yes, it's going to be an elusive one.

To be clear, I am normally able to export data.  But it just stops working at some point.  And then I need to restart the program to enable the feature again. 

In this case it was on a Postgres database.  Only text and number data, and only a few columns, but many rows (100,000+).

This has happened several times for me.  In the most recent case, I had the program running for several hours, happily selecting and exporting the same dataset (different data, same structure).  Then all of a sudden, it won't create the file.  No error or warning.  I can try again and again but it won't do it.

Save my query, restart the program, execute the query again, and exporting works.

**Comment by msharp** [comment] 2018-07-26 07:21
Another thing, that seems related to this, is that the application loses the ability to save files (the SQL scripts) and reports a permission error - https://www.dropbox.com/s/4htiwct10r39925/Screenshot%202018-07-26%2017.15.57.png?dl=0

And neither can it open files - https://www.dropbox.com/s/c8uton91et0jb7v/Screenshot%202018-07-26%2017.20.32.png?dl=0

Again, quitting and restarting the application, resolves the issue.

**Comment by hankinsoft** [comment] 2019-03-28 12:27
Hi,
This issue was related to https://github.com/hankinsoft/SQLPro/issues/99 which has been resolved by Apple with macOS updated. If you still see the issue, please ensure that you are using the latest version of macOS. If you are, and continue to see the issue, please let me know.

**Closed by hankinsoft** 2019-03-28 12:28 UTC
