### ISSUE TITLE
The bottom row of the last result set in a block of select statements is cut off

### ISSUE THREAD

**Issue by GaryMeyers1** [hankinsoft/SQLPro#817] opened 2022-08-02 01:51 UTC
In one of the attached screen shots, the select statement shows the last row in the grid as expected.  However, when the same select statement is run as the fourth of four select statements, the bottom row is cut off and is not shown in the grid.  Similar results are seen when the select statement is the second of two select statements so there's nothing special about four queries.

<img width="1215" alt="bottom row cut off" src="https://user-images.githubusercontent.com/60852956/182274546-13c51d7e-987f-457a-bd52-7da12ef0c129.png">
<img width="1061" alt="can see bottom row" src="https://user-images.githubusercontent.com/60852956/182274550-c18369ac-4e25-45fc-8a5c-263e3510296f.png">

**Comment by hankinsoft** [comment] 2022-08-08 14:16
Closing as a duplicate of https://github.com/hankinsoft/SQLPro/issues/712.

**Closed by hankinsoft** 2022-08-08 14:16 UTC
