### ISSUE TITLE
Snowflake: Temporary Table Gone

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#408] opened 2020-04-10 17:30 UTC
I needed to remove many duplicates that had been entered into a table. I created a temporary table with the production table's data, did the changes I needed and verified that things were good. Then I was just about to hit execute on truncating the production table's data before doing an insert of everything from the temp table back into the production table, when I decided I'd better just double check one more time that the temp table had the right data in it.

When I tried to query it, it said it did not exist. This was important data to the company, and all of it would have been deleted. When I was studying the Snowflake docs before doing any of this, it said that a temporary table remained in existence until a) you explicitly dropped it or b) your session terminated.

I didn't explicitly drop the table, and couldn't think of any way I'd terminated the session. My internet connection was active, I didn't close SQLPro Studio or any tabs, alter my session, etc. I did have to cancel a running Snowflake query (in the same tab) between when I created the temp table and when it was gone. Does SQLPro Studio terminate a session in order to cancel a running Snowflake query?

It definitely worries me to think of how close I came to losing all of that data. After that, I just used a standard table rather than temporary.

Thoughts?

What are your thoughts on having an alert pop up if a session is terminated? That could alert the user of anything relevant in case they had any temporary objects (database, schema, table, etc.) in use beforehand.

I would upload or email the log, but it has been a while since I've cleared it out (so it's extremely long and I'm not sure where I can cut things off to still include what's needed) and there are a lot of company IP addresses, table names, database names, etc. in there and I'm afraid I might miss one.

SQLPro Studio 2020.35 (Build 110664.5)
macOS 10.15.4 (19E287)
Snowflake 4.11.0

**Comment by hankinsoft** [comment] 2020-04-10 18:02
> I did have to cancel a running Snowflake query (in the same tab) between when I created the temp table and when it was gone. Does SQLPro Studio terminate a session in order to cancel a running Snowflake query?

Yes, SQLPro does terminate the session in the event of a cancellation.

> What are your thoughts on having an alert pop up if a session is terminated? That could alert the user of anything relevant in case they had any temporary objects (database, schema, table, etc.) in use beforehand.

Possibly -- I think a blocking alert would be too invasive. Maybe something like a Toast notification. It's something I will have to think about the proper way to implement.

**Comment by jim256** [comment] 2020-04-10 19:24
@hankinsoft 

> Yes, SQLPro does terminate the session in the event of a cancellation.
I'm not educated enough to know - is that the ideal way to cancel a running query? FWIW, the Snowflake Web UI will issue an abort request using the GUID of the query being run. I don't really know if that's truly a literal query ID or a session ID, though.

**Comment by hankinsoft** [comment] 2020-04-10 19:36
> I'm not educated enough to know - is that the ideal way to cancel a running query? FWIW, the Snowflake Web UI will issue an abort request using the GUID of the query being run. I don't really know if that's truly a literal query ID or a session ID, though.

Sorry, closing the client is not the only part of the process for cancelling the query. The current statement is also terminated via the snowflake api.

What do you mean by 'issue an about request'? Thats not something I've heard of for Snowflake.

> I think this depends on the answer to the above, but in the case of losing potentially a very significant amount of potentially-crucial data...

I need to think on this one a bit more. I agree that the potential of losing data you would probably want something invasive but at the same time I believe this is probably an edge case, so I wouldn't want to display it for the vast majority of users. Adding a user option for this might be the best way.

**Comment by hankinsoft** [comment] 2020-04-10 19:45
I think I see what you mean the webui does. I’m going to investigate this for the next build.

**Comment by hankinsoft** [comment] 2020-04-10 21:23
I think I e come up with a solution that will sort us both - the reason I kill the connection on cancellation is an inheritance - I kill the connection on an error (and a cancellation returns a ‘query was cancelled’ error).

What I propose:
Instead of killing the connection on an error,  detect ‘recoverable’ vs ‘unrecoverable’ errors. An unrecoverable error would be something such as ‘lost connection to server’. An unrecoverable error requires a new connection before any questions can be run. In this case I would be ok to display some sort of user-interrupting alert to the user before continuing.

Thoughts?

**Comment by jim256** [comment] 2020-04-14 01:38
@hankinsoft I think that sounds like a solid approach.

**Comment by jim256** [comment] 2020-06-26 17:07
Hey @hankinsoft, I just wanted to touch base here. I've needed to switch to temporary tables instead of CTEs for a few extra-heavy queries lately.

Say you've got 3 temporary tables in your query, and the 1st and 2nd are working 100% as desired, and you're just working on ironing out the 3rd. One advantage to the temp table approach over CTEs is that you don't have to re-run the first two queries every time, even if the 3rd depends on them, because the data is already there. However, this makes it so you cannot ever cancel a running query (which can be very handy when developing / testing) because SQLPro Studio will terminate the session and therefore drop all temp tables.

Any thoughts here? Would it be reasonable to not kill the session each time a query is canceled?

**Comment by jim256** [comment] 2020-06-29 20:33
This also happens if a subsequent query fails.

For example, if I have one statement that runs and creates and populates a temp table, then another statement which queries that temp table, the temp table will get "deleted" (session terminated) if the second statement / query fails, even though the creation and population of the temp table were successful.

**Comment by hankinsoft** [comment] 2020-06-30 18:50
For the next build, I've got this fixed up so that cancelling a query will no longer kill the connection.

> This also happens if a subsequent query fails.

I'm not able to reproduce this. Check the following gif (sorry, my gif making skills are terrible today):

![CleanShot 2020-06-30 at 15 46 46](https://user-images.githubusercontent.com/3160528/86165045-22ab0100-bae9-11ea-8daa-85314ba444a8.gif)

In the above example I:

1. Create the temp table
2. Select from the temp table
3. Run a failed query
4. Select from the temp table.
5. Cancel a query (it takes me a few attempts as its a quick query).
6. Select from the temp table again.


Is steps 3-4 what you mean by `if a subsequent query fails`?

I'm also working on adding a notification if the tabs connection is disconnected (ie, the temp tables are dropped).

**Comment by jim256** [comment] 2020-06-30 20:26
@hankinsoft , so sorry to have wasted your time. I can't replicate this now either. I *thought* it was happening when I ran executed multiple statements together, where the failure of a 3rd statement could drop the session and cause the temp table created by the 1st statement to be non-existent.

If I end up experiencing this, I'll let you know.

> For the next build, I've got this fixed up so that cancelling a query will no longer kill the connection.
AWESOME!! Thanks a lot

**Comment by hankinsoft** [comment] 2020-07-06 12:08
2020.61 is now available which adds this. If you get the chance, please give it a test and confirm its working as you would expect.

I still do not have the 'notifications' for when the tab disconnects/reconnects as of yet, so I will keep this issue open.

**Comment by jim256** [comment] 2020-07-06 15:31
@hankinsoft, temp table seems to persist even after query cancellation! 💪  Thanks again.

I'll note, though, that the app no longer states that the query was canceled, but rather just says "Statement executed successfully." - not sure if this is intentional or not.

**Comment by jim256** [comment] 2020-07-08 17:50
@hankinsoft, FWIW, I just had it happen again where I was executing a few statements and the failure of one of them caused the loss of a temporary table created prior to it. I cleared my log, ran the same code gain to replicate the error so I could send you the log, and the next time the temp table was not dropped. So I *think* this may still be an intermittent issue somehow.

**Comment by hankinsoft** [comment] 2020-07-09 12:24
Thanks - the next part I'm working on for this is the notifications when the tabs client disconnects/reconnects. Once that's in, I'll request logs for when you see the disconnects. That should help figure out where this is happening.

I was thinking yesterday - I was curious if as a workaround, could you use transient tables instead of temp tables? They don't disappear when the client disconnects (until implicitly dropped).

**Comment by jim256** [comment] 2020-07-09 20:27
Thanks for throwing that out there. I've thought about using those, but my use case would make it not really make sense to require that I drop them after every session. Most of the time, it is very instance-specific transformations I do just before outputting results to something else.

**Comment by jim256** [comment] 2020-07-16 18:00
It just happened again. This time it was because I had used an invalid table alias in the query that failed.

It was like this:
CREATE OR REPLACE TEMP TABLE _first AS
...
;
CREATE OR REPLACE TEMP TABLE _second AS
...
;
CREATE OR REPLACE TEMP TABLE _third AS
...
;

_third failed because I used an non-existent table alias ("o" instead of "ord"). It used _second in it's FROM. I corrected the table alias and tried to run from "CREATE OR REPLACE TEMP TABLE _third..." onward, and it errored saying that _second did not exist.


SQLPro Studio 2020.61 (Build 110689.5)
macOS 10.15.5 (19F101)
Snowflake 4.24.1

**Comment by jim256** [comment] 2020-10-08 15:33
I've honestly been having this a ton lately (for probably the last 4 ish versions). I'll run 3 statements that create a few temp tables, then immediately thereafter try to query the temp table and get the error that it doesn't exist. Then I run them again and try to select again (without changing any SQL), and it works.

Previously I thought it was only caused when there was an error in the SQL. I think that can still cause it to drop the session, but now it's also for sure losing it when there are no SQL errors.

Log file:
[SQLPro-TempTableDoesntExist.log](https://github.com/hankinsoft/SQLPro/files/5349021/SQLPro-TempTableDoesntExist.log)


SQLPro Studio 2020.88 (Build 110729.5)
macOS 10.15.7 (19H2)
Snowflake 4.33.1

**Comment by jim256** [comment] 2020-10-14 22:02
This just happened again. This time I highlighted the entire script, including the temp table creation and the subsequent query from the temp table, and as soon as it hit that last query to select from the temp table, it said it didn't exist.

This query was like this

USE SCHEMA [schema_name];

CREATE OR REPLACE TEMP TABLE _my_table AS
...
;

SELECT col1, SUM(col2)
FROM _my_table
GROUP BY 1
;

Here's the output

<img width="804" alt="image" src="https://user-images.githubusercontent.com/15026225/96050093-4abf3580-0e36-11eb-9e6e-fec675b1157f.png">

Log file:
[com.hankinsoft.osx.sqlprostudio 2020-10-14--21-52-53-511.log](https://github.com/hankinsoft/SQLPro/files/5381058/com.hankinsoft.osx.sqlprostudio.2020-10-14--21-52-53-511.log)

**Comment by jim256** [comment] 2020-11-13 16:09
Yesterday, I was talking with a friend I'd recommended SQLPro Studio to who's been using it for almost a year.

He said he encountered a similar issue with Postgres / Redshift. He noted that when he runs a more complex query that he loses all of his temp tables.

**Comment by jim256** [comment] 2020-11-19 16:19
Not actually sure if it's the same issue on Redshift. I was helping him with a query yesterday, and I noticed that when he went to execute a subsequent query, it said something like it'd lost connection to the server (don't recall the exact error). In that case, I wouldn't be surprised if it lost the session (and therefore the temp tables).

**Comment by jim256** [comment] 2020-11-19 16:53
I also realized that I'm not sure if the previous screenshots / error logs I posted were of the right error, since it says "invalid identifier", so I wanted to re-post screenshots and logs of where the table was created and then immediately thereafter not found.

I also wanted to provide additional details and say that I've noticed that it's more consistent with large data sets. If the query that populates the temp table, for example, takes 2 minutes to execute (very rare), then the temp table is never there, and I have to go use another app for that particular task. For a task like this, temp tables is really the only way to go because 2 minutes to populate a temp table in Snowflake is a very, very long time, so if I tried to run the subsequent queries by having the base query in a CTE or something, it would take even longer, and I'd have to consume that wait time every time I ran a query on that dataset. Since temp tables is the only way to go for something like this and SQLPro Studio cannot retain the temp table for these particular situations, these situations alway forces me out of SQLPro Studio.

If it's for lighter queries, the error is less rare, but certainly still happens frequently enough to cause frustration and decrease productivity.

(the `_` are simply because I prefix my temp table names with `_` to avoid accidental same-naming with real tables and to make them easily distinguishable as temp tables)

Query output from creating a couple of temp tables, the last one being `_FINAL`:
<img width="722" alt="image" src="https://user-images.githubusercontent.com/15026225/99695869-4dbbd000-2a4b-11eb-9234-45904c97c20d.png">

Query and output immediately thereafter of trying to query the temp table `_FINAL`:
<img width="736" alt="image" src="https://user-images.githubusercontent.com/15026225/99695916-5ca28280-2a4b-11eb-987d-45053f18aba7.png">

I don't think it can actually be not authorized, because I'm connected as the `ACCOUNTADMIN` role (highest in Snowflake). I manually checked the schemas afterward, and that temp table doesn't appear (whereas temp tables normally do). I'm also able to copy / paste the queries into the Snowflake web console and execute them in the same order there without issue.

Log:
[com.hankinsoft.osx.sqlprostudio 2020-11-19--16-29-38-758.log](https://github.com/hankinsoft/SQLPro/files/5568363/com.hankinsoft.osx.sqlprostudio.2020-11-19--16-29-38-758.log)



I haven't personally ever experienced anything like this with Postgres / Redshift.

I really hope all these details are helpful! Please let me know if there's anything else at all I can provide or test. I'm happy to jump all over it as I'm desperate to solve this one.

SQLPro Studio 2020.100 (Build 110751.5)
macOS 11.0.1 (20B29)
Snowflake 4.38.1

**Comment by hankinsoft** [comment] 2020-11-19 18:41
Can you grab https://d3fwkemdw8spx3.cloudfront.net/temp/SQLProSnowflake-T1.zip and use that for snowflake? I've added extra logging around disconnects to try and figure out where that is happening. Also, I've added additional logging around the JDBC. If you could try that separately and post the log that would be great.

**Comment by hankinsoft** [comment] 2020-11-19 22:13
Update: I might have found a combination of canceling query + threading issue which can cause a tab to get a ‘new client’ without disconnecting the old one. I think that might be what’s happening in this case. It’s a bit flakey to reproduce it, but I might be getting close.

**Comment by jim256** [comment] 2020-11-19 22:56
Such good news! THANK YOU for diving in here.

And yes, happy to. Will repost here afterward.

Also, FWIW, this query seems to do it every time:

```
USE SCHEMA PUBLIC;


CREATE OR REPLACE TEMP TABLE _credits_per_query AS

	SELECT
		mh.NAME WAREHOUSE
	,	DATE_TRUNC('MONTH', mh.START_TIME)::DATE USAGE_MONTH
	,	mh.SERVICE_TYPE
	,	mh.START_TIME
	,	mh.END_TIME
	,	mh.CREDITS_USED
	,	qh.QUERY_ID
	,	qh.QUERY_TEXT
	,	qh.QUERY_TYPE
	,	qh.USER_NAME
	,	qh.ROLE_NAME
	,	qh.START_TIME QUERY_START_TIME
	,	qh.END_TIME QUERY_END_TIME
	,	qh.EXECUTION_TIME
	,	(qh.EXECUTION_TIME / SUM(qh.EXECUTION_TIME) OVER (PARTITION BY mh.NAME, mh.START_TIME, mh.END_TIME)) * 100 PCT_CREDIT_USED_BY_QUERY
	,	((PCT_CREDIT_USED_BY_QUERY / 100) * mh.CREDITS_USED) CREDIT_USED_BY_QUERY

	FROM
		SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY mh
		JOIN SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY qh ON mh.ENTITY_ID = qh.WAREHOUSE_ID
			AND qh.START_TIME BETWEEN mh.START_TIME AND mh.END_TIME

	WHERE
		TRUE
	AND	qh.WAREHOUSE_SIZE IS NOT NULL -- Eliminate queries served by Cloud Services layer
	AND mh.START_TIME > DATE_TRUNC('MONTH', ADD_MONTHS(CURRENT_DATE(), -6)) -- Edit as per analysis period
--	AND	qh.EXECUTION_STATUS = 'SUCCESS' -- Disabled since failed execution will also consume compute
;


SELECT
	*

FROM
	_credits_per_query cpq
```

**Comment by jim256** [comment] 2020-11-19 23:31
Failure log from running the above statements (first two together, third one after):

[com.hankinsoft.macos.sqlpro-for-snowflake 2020-11-19--23-26-16-699.log](https://github.com/hankinsoft/SQLPro/files/5570303/com.hankinsoft.macos.sqlpro-for-snowflake.2020-11-19--23-26-16-699.log)

**Comment by hankinsoft** [comment] 2020-11-20 14:55
Hmmm, I'm not able to run that query - I get an error that the database SNOWFLAKE is unavailable. Are you specifying a ROLE by any chance? Or a specific warehouse? (Either of those would also explain why the JDBC driver is not working as I have not set those up yet).

In addition, can you try this build and submit the logs? I've made a change, so it MIGHT resolve the issue - but if not the additional logs should help:

https://d3fwkemdw8spx3.cloudfront.net/temp/SQLProSnowflake-T2.zip

**Comment by jim256** [comment] 2020-11-20 16:24
I do have a role specific (`ACCOUNTADMIN`). I don't know which roles by default have access to the Snowflake database. I think it comes default, though, so I'd imagine you'd have it?

Trying this now. I didn't know I shouldn't have role specified, so I'll also try it (and the JDBC connector) without that.

**Comment by jim256** [comment] 2020-11-20 16:27
First log file (still had role specified):
[com.hankinsoft.macos.sqlpro-for-snowflake 2020-11-20--16-21-06-026.log](https://github.com/hankinsoft/SQLPro/files/5574793/com.hankinsoft.macos.sqlpro-for-snowflake.2020-11-20--16-21-06-026.log)

Side note - did you remove database names from the logs!? :smiley:  I was just going through it to remove them as usual and didn't see them. That'd sure be great.

**Comment by jim256** [comment] 2020-11-20 16:55
:open_mouth: without a role or warehouse specified, it worked 2x in a row. If this fixes it, that'd sure be fantastic.

Log of the 2nd time:
[com.hankinsoft.macos.sqlpro-for-snowflake 2020-11-20--16-47-15-706.log](https://github.com/hankinsoft/SQLPro/files/5574978/com.hankinsoft.macos.sqlpro-for-snowflake.2020-11-20--16-47-15-706.log)

**Comment by hankinsoft** [comment] 2020-11-21 13:21
Hi,
I've made a complete overhaul of how 'connection pooling for tabs' works. Can you give this build a try:

https://d3fwkemdw8spx3.cloudfront.net/temp/SQLProSnowflake-T3.zip

It should work regardless of the warehouse, role, etc.

(No changes for JDBC on this one - just around the temp tables issue).

**Comment by jim256** [comment] 2020-11-22 05:26
:partying_face: Tried this several times today and it worked every single time. I tried it a few times in the same tab, again in a new tab, disconnecting from the DB and reconnecting, and also quitting and re-starting the app. Never failed :crossed_fingers: 

I also didn't notice any bugs / issues. To be fair, though, my testing was very basic - I simply ran the create statement, then ran the select statement (with a LIMIT 500 on it) a bunch of times.

THANK YOU for diving into this one!!!!

**Comment by hankinsoft** [comment] 2020-11-23 13:22
Great! I'm just trying to get #537 fixed up then I will submit a fixed SQLPro Studio build with this to the app store.

**Comment by hankinsoft** [comment] 2020-11-24 12:43
This should now be available in build 2020.102.

**Comment by jim256** [comment] 2020-11-24 18:36
Tested in 2020.102 1x and it's working so far. This is SO NICE to not have those constantly dropping. I know you've got a lot of improvements you're always simultaneously working on. Thanks for making this one happen.

**Comment by hankinsoft** [comment] 2020-11-24 18:40
Glad to hear its working. I'm going to keep this one open for a week or so then close it unless you see it happen again.

One note: Using the server/database picker dropdown WILL create a new connection (as you switch databases, a new connection is created). So using this dropdown will loose any temporary tables.

**Comment by jim256** [comment] 2020-11-24 19:58
Noted, thanks. Very good to know.

**Closed** 2021-01-25 19:33 UTC
