### ISSUE TITLE
Multiple cursor selection

### ISSUE THREAD

**Issue by mkormendy** [hankinsoft/SQLPro#200] opened 2018-07-03 16:52 UTC
Feature as seen here: http://www.youtube.com/watch?v=i2SVJa2EGIw

CodeMirror implements this feature here: https://github.com/codemirror/CodeMirror/issues/778

Could we have this implemented?

**Comment by hankinsoft** [comment] 2019-03-28 11:22
At the moment I currently have no plans for this feature.

**Comment by mkormendy** [comment] 2019-03-28 13:37
But this is such a great and powerful feature. Why not?

**Comment by hankinsoft** [comment] 2019-03-28 13:41
Hi,
Two reasons at the moment:

1. Lack of requests for it (if I receive more requests I would consider
adding support).
2. Difficulty to implement.

Unfortunate those two reasons combined make it a very low priority item.

**Comment by mkormendy** [comment] 2019-03-28 13:44
What do you use as the editor for the application? If you’re using the ultra popular CodeMirror, then it’s a simple configuration line. If not, I can see the difficulty.

**Comment by hankinsoft** [comment] 2019-03-28 13:55
Hi,
No, SQLPro uses the native macOS NSTextView with custom code for syntax
highlighting, autocomplete, etc. Unfortunate codemirror ran much slower
(especially on large files) when I tried it many years ago.

**Comment by mkormendy** [comment] 2019-03-29 13:20
I see, well I found this re: multi-line editing for NSTextView:

https://stackoverflow.com/questions/37691202/multi-line-nstextfield-not-working

**Comment by hankinsoft** [comment] 2020-07-02 14:37
Reopening as I've had more requests for this.

**Comment by jim256** [comment] 2020-09-03 18:30
@hankinsoft love that this is coming along. Two questions:
1. I'm able to select multiple lines using the mouse (while holding CMD). Is it possible to select multiple lines using just the keyboard. I would personally vote for the default VS Code implementation of Shift + Option + CMD + arrow key.
2. It looks like I can type, delete, arrow, etc., but I'm not able to go to the end of all lines by hitting CMD + right arrow or Ctrl + E. Both remove the multi-line cursor and just take me to the end of the first line.

**Comment by jim256** [comment] 2020-09-03 19:10
I also just realized that it doesn't support pasting. So if I select multiple lines and then hit CMD + V (to, for example, insert "SUM(" in front of all lines, it pastes it to the first line only and the other cursors disappear.

**Comment by hankinsoft** [comment] 2020-09-11 11:47
> 1. I'm able to select multiple lines using the mouse (while holding CMD). Is it possible to select multiple lines using just the keyboard. I would personally vote for the default VS Code implementation of Shift + Option + CMD + arrow key.
> 2. It looks like I can type, delete, arrow, etc., but I'm not able to go to the end of all lines by hitting CMD + right arrow or Ctrl + E. Both remove the multi-line cursor and just take me to the end of the first line.
> 3. I also just realized that it doesn't support pasting. So if I select multiple lines and then hit CMD + V (to, for example, insert "SUM(" in front of all lines, it pastes it to the first line only and the other cursors disappear.

These are all fixed in the latest app store version of SQLPro Studio. Please give it a try if you get the chance.

**Comment by jim256** [comment] 2020-09-11 16:01
This is awesome!!!!

Only thing that doesn't seem to work now is rapid deleting. If I have two lines highlighted and use Option + Delete or CMD + Delete, the additional cursors disappear and the delete only happens on one line.

**Comment by hankinsoft** [comment] 2020-09-23 11:54
FYI `Option + Delete` and `CMD + Delete` have been fixed for the latest available version. If you get the chance, please let me know if that sorts everything out. I've also done a quick support article on this as well at https://www.sqlprostudio.com/blog/11-multi-cursors.

**Comment by mkormendy** [comment] 2020-09-23 14:24
This makes me super happy, you have no idea!!!!

**Comment by jim256** [comment] 2020-09-28 19:36
I am using this like crazy. Thank you so much. Allows me to keep my workflow in the app a lot more. About the only issue I see with it now is this

<img width="99" alt="image" src="https://user-images.githubusercontent.com/15026225/94477472-2ead6a00-018f-11eb-8dbd-78ec3144fbf7.png">

If I've got multiple lines selected, with a leading comma, using tabs for indentation, the cursors don't align. Log file just contained "Application is becoming active". Seems to work just fine when using the mouse. They are only misaligned when using the keyboard shortcuts.

**Comment by hankinsoft** [comment] 2020-09-29 13:02
Fixed for the next build.

**Comment by jim256** [comment] 2020-10-09 22:33
I think `Option + Delete` is still functioning differently than expected. If I highlight multiple lines, then use that combination, it removes the additional cursors and performs the delete on only one line.

**Comment by hankinsoft** [comment] 2020-11-16 12:44
This should now be working properly. From my tests, Option + Delete (and Option + Backspace) should match VS Code.

**Comment by jim256** [comment] 2020-11-16 20:14
I'm seeing the same behavior as previously.
Test text:

```
LINE OF TEXT
LINE OF TEXT
LINE OF TEXT
LINE OF TEXT
LINE OF TEXT
```

If I place the cursor between the "T" and "E" of "TEXT" on lines 3 and then use Shift + Option + Command + Down Arrow to add a cursor in the same spot on lines 4 and 5, then press Option + Delete, it removes the cursors from lines 4 and 5 and performs the delete on line 3, leaving me with:

```
LINE OF TEXT
LINE OF TEXT
LINE OF EXT
LINE OF TEXT
LINE OF TEXT
```

Log file:
[com.hankinsoft.osx.sqlprostudio 2020-11-16--19-48-07-923.log](https://github.com/hankinsoft/SQLPro/files/5549410/com.hankinsoft.osx.sqlprostudio.2020-11-16--19-48-07-923.log)


SQLPro Studio 2020.96 (Build 110739)
macOS 11.0.1 (20B29)

**Comment by mkormendy** [comment] 2020-11-16 22:15
> I'm seeing the same behavior as previously.
> Test text:
> 
> ```
> LINE OF TEXT
> LINE OF TEXT
> LINE OF TEXT
> LINE OF TEXT
> LINE OF TEXT
> ```
> 
> If I place the cursor between the "T" and "E" of "TEXT" on line 3 and then use Shift + Option + Command + Down Arrow to add a cursor in the same spot on lines 4 and 5, then press Option + Delete, it removes the cursors from lines 4 and 5 and performs the delete on line 3, leaving me with:
> 
> ```
> LINE OF TEXT
> LINE OF TEXT
> LINE OF EXT
> LINE OF TEXT
> LINE OF TEXT
> ```
> 
> Log file:
> [com.hankinsoft.osx.sqlprostudio 2020-11-16--19-48-07-923.log](https://github.com/hankinsoft/SQLPro/files/5549410/com.hankinsoft.osx.sqlprostudio.2020-11-16--19-48-07-923.log)
> 
> SQLPro Studio 2020.96 (Build 110739)
> macOS 11.0.1 (20B29)

In this case I just use the mouse, select that specific spot and alt + dragdown with the pointer and then hit delete to delete the T’s.

**Comment by jim256** [comment] 2020-11-16 22:25
Hey, @mkormendy. Thanks for chiming in.
I'm able to delete all the T's using the keyboard method as well.
This is in reference to using Option + delete (in order to delete more than one character at a time). Doing so removes the other cursors.

**Comment by hankinsoft** [comment] 2020-11-17 17:32
Thanks, both - I think I have this reproduced.

**Comment by jim256** [comment] 2020-11-17 18:04
I just noticed the same issue (all cursors are removed except the first one) if I make multiple cursors and then try to type `"`. I think my having to use Shift could be involved.

**Comment by hankinsoft** [comment] 2020-11-17 18:20
Not sure I'm following what you mean:

![CleanShot 2020-11-17 at 14 20 03](https://user-images.githubusercontent.com/3160528/99430685-0fee6880-28e0-11eb-88b5-a2e78a3075a7.gif)

**Comment by mkormendy** [comment] 2020-11-17 18:26
@jim256 after using Shift + Option + Command + Down Arrow to add a cursor in the same spot for subsequent lines, I'm not sure what you're trying to achieve by pressing Option + Delete.

In VSCode it simply performs a backspace and deletes the previous character to the cursor on all lines with a cursor. That's the same as hitting the delete key (which does what you expect).

**Comment by mkormendy** [comment] 2020-11-17 18:30
> @jim256 after using Shift + Option + Command + Down Arrow to add a cursor in the same spot for subsequent lines, I'm not sure what you're trying to achieve by pressing Option + Delete.
> 
> In VSCode it simply performs a backspace and deletes the previous character to the cursor on all lines with a cursor. That's the same as hitting the delete key (which does what you expect).

Oh I see now, the Option + Delete is technically a "word backspace delete", where it removes the entire word previously.

![Nov-17-2020 12-30-11](https://user-images.githubusercontent.com/1437667/99431616-aa46b000-28d0-11eb-80a4-89db37f7b0c3.gif)

**Comment by hankinsoft** [comment] 2020-11-17 18:33
> Oh I see now, the Option + Delete is technically a "word backspace delete", where it removes the entire word previously.

Yep - This is what I've fixed for the next build. macOS calls it 'delete word backwards'.

**Comment by hankinsoft** [comment] 2020-11-17 18:34
I'm not sure about the:

> I just noticed the same issue (all cursors are removed except the first one) if I make multiple cursors, go to the end of a line, then try to type ".
> 
> If I try to type " without going to the end of the line first, it works fine.
> If I go to the end of the line and try to type something else that requires the shift key (like ?), that also works fine.

Issue though. I don't quite understand (I posted a gif of me trying it up earlier?).

**Comment by jim256** [comment] 2020-11-17 22:35
I tried the same thing as your GIF and that worked fine for me as well. If I remove the `;`, then it doesn't work.

Log:
[com.hankinsoft.osx.sqlprostudio 2020-11-17--22-25-56-948.log](https://github.com/hankinsoft/SQLPro/files/5556593/com.hankinsoft.osx.sqlprostudio.2020-11-17--22-25-56-948.log)

Screen recording (needs to have .txt swapped for .mov):
[multi-cursor_problem.txt](https://github.com/hankinsoft/SQLPro/files/5556598/multi-cursor_problem.txt)

SQLPro Studio 2020.97 (Build 110745.5)
macOS 11.0.1 (20B29)

**Comment by hankinsoft** [comment] 2020-11-18 12:40
Ahhhh, figured it out. You have enabled autoclose bracket and quotes preferences on and I don't. Reproduced and fixed for the upcoming 2020.100 build.

**Comment by hankinsoft** [comment] 2020-11-19 12:17
2020.100 is now available. If you get the chance, please give it a try and let me know if everything works as expected.

**Comment by jim256** [comment] 2020-11-19 16:15
I think it works!

Unfortunately...discovered another issue. And FWIW, now that I see this, I think I've seen it before (in earlier versions).

If I make a few cursors, and one of them is on the last line of the file, and I then use CMD + Right Arrow to jump to the end of the line, the last cursor instead jumps to the beginning of the file.

Screen recording (change .txt to .mov) and log attached:
[Multi-cursor_End-of-line_Issue.txt](https://github.com/hankinsoft/SQLPro/files/5568136/Multi-cursor_End-of-line_Issue.txt)
[com.hankinsoft.osx.sqlprostudio 2020-11-19--16-09-57-412.log](https://github.com/hankinsoft/SQLPro/files/5568140/com.hankinsoft.osx.sqlprostudio.2020-11-19--16-09-57-412.log)



macOS 11.0.1 (20B29)
SQLPro Studio 2020.100 (Build 110751.5)

**Comment by hankinsoft** [comment] 2020-11-23 13:46
Thanks, fixed for the next build. Should be available later this week.

**Comment by hankinsoft** [comment] 2020-11-24 12:43
This should now be available in build 2020.102.

**Comment by hankinsoft** [comment] 2021-01-11 12:40
I think everything here has been sorted? I'll close this in a few days unless anyone objects.

**Comment by jim256** [comment] 2021-01-11 22:39
It's been working very well for me. Thanks for your persistence on this one! A very handy feature.

**Comment by hankinsoft** [comment] 2021-01-12 14:16
Great, I'm going to close it. If anyone runs into anything related, please feel free to re-open or create a new issue.

**Closed by hankinsoft** 2021-01-12 14:16 UTC
