### ISSUE TITLE
Export/Import Connections

### ISSUE THREAD

**Issue by jeisaacs** [hankinsoft/SQLPro#852] opened 2022-11-10 14:02 UTC
**Is your feature request related to a problem? Please describe.**
I would like to backup my connections, so that if I do a clean install of SQLPro Studio, I can get up and running ASAP

**Describe the solution you'd like**
A simple import/export would suffice - with the option of including the username/passwords for the servers.

**Describe alternatives you've considered**
Saving the credentials in 1Password, however adding them manually takes time.

**Comment by hankinsoft** [comment] 2022-11-10 16:19
Closed as a duplicate of #146. It's on my todo list, however because the connections sync over iCloud it's been a fairly low priority.

**Closed by hankinsoft** 2022-11-10 16:19 UTC

**Comment by jeisaacs** [comment] 2022-12-16 08:07
Hi @hankinsoft - is there a way to delete what is stored in iCloud - as I believe it is corrupt as the changes I make don't seem to save.

**Comment by hankinsoft** [comment] 2022-12-16 17:19
If you search your iCloud Keychain for 'recentconnection' and remove all entries where the account is displayed as <DatabaseType>RecentConnection that will remove everything.

<img width="1123" alt="Screenshot 2022-12-16 at 1 18 29 PM" src="https://user-images.githubusercontent.com/3160528/208153233-3c236d28-8783-4b52-959e-4ee2fa30862e.png">
