### ISSUE TITLE
Export entire Database?

### ISSUE THREAD

**Issue by mikebronner** [hankinsoft/SQLPro#64] opened 2016-12-28 19:25 UTC
I have clients with lots of tables, and frequently need to export all their data. Is there a way to export an entire database without going through each table manually? (Or perhaps selecting multiple tables to export at once?)

**Comment by hankinsoft** [comment] 2019-04-10 11:47
Closing this as a duplicate of #101 as it has more follows. MSSQL export options have been added to the latest studio build and other export options will be available soon.

**Closed by hankinsoft** 2019-04-10 11:47 UTC
