### ISSUE TITLE
Bug: Snowflake: Fully-qualified objects not recognized in SQL Editor

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#415] opened 2020-04-21 20:57 UTC
If I fully qualify a table name in the FROM with [DATABASE_NAME].[SCHEMA_NAME].[TABLE_NAME], and then right-click on one of those table names, the context menu says "no object selected" and all relevant selections are disabled.

Also seems like autocomplete doesn't work for these objects. If I have a table aliased as "vp", for example, and then type "vp." into my WHERE, no column suggestions are provided.
If I have a database named, "JIMS_DB", for example, and I type "JIMS_DB." into my FROM, no schema suggestions are provided.

Log file:
[com.hankinsoft.osx.sqlprostudio 2020-04-21--20-50-30-992.log](https://github.com/hankinsoft/SQLPro/files/4512564/com.hankinsoft.osx.sqlprostudio.2020-04-21--20-50-30-992.log)

SQLPro Studio 2020.35 (Build 110664.5)
macOS 10.15.4 (19E287)
Snowflake 4.13.2

**Comment by hankinsoft** [comment] 2020-04-23 12:07
Good morning. I'm going to close this as a duplicate of #404 (all 'objects' for autocomplete, aliases, the context menu lookup, etc use the same engine for finding objects).

**Closed by hankinsoft** 2020-04-23 12:07 UTC

**Comment by jim256** [comment] 2020-05-05 16:43
@hankinsoft, I meant to say a while ago that I can understand your above comment.

However, the reason that I still chose to make it a separate issue is that I was thinking that it would not slow down the autocomplete if objects outside the current schema were only enabled if fully qualified.

For example, I understand that you don't want to have autocomplete search everything for performance reasons, given that some of your customers have thousands of DBs. So I'd understand not completing database names, schema names, or table names outside the current context.

But, if I fully qualify an object name outside the current context, I was thinking that it could recognize just that fully-qualified object for the context menu, autocomplete, etc.

Thoughts?
